-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.9', '6.0.8_6.0.9_upgrade');

--
-- modèles de documents : séparation BATCH/LOCAL pour les déclarations PM & APM
--

INSERT INTO MODELE_DOCUMENT (ID, LOG_CDATE, LOG_MDATE, LOG_CUSER, LOG_MUSER, TYPE_DOCUMENT, PERIODE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, CURRENT_DATE, '[Installation SIPM]', '[Installation SIPM]', TYPE_DOCUMENT || '_LOCAL', PERIODE_ID
	FROM MODELE_DOCUMENT
	WHERE TYPE_DOCUMENT IN ('DECLARATION_IMPOT_PM', 'DECLARATION_IMPOT_APM');
UPDATE MODELE_DOCUMENT SET TYPE_DOCUMENT=TYPE_DOCUMENT || '_BATCH' WHERE TYPE_DOCUMENT IN ('DECLARATION_IMPOT_PM', 'DECLARATION_IMPOT_APM');

--
-- modèles de feuilles de document
--

-- le champ NO_FORMULAIRE devient un entier dans le champ NO_CADEV
ALTER TABLE MODELE_FEUILLE_DOC ADD (NO_CADEV NUMBER(4,0));
UPDATE MODELE_FEUILLE_DOC SET NO_CADEV=TO_NUMBER(TRIM(NO_FORMULAIRE));
ALTER TABLE MODELE_FEUILLE_DOC MODIFY (NO_CADEV NUMBER(4,0) NOT NULL);
ALTER TABLE MODELE_FEUILLE_DOC DROP COLUMN NO_FORMULAIRE;
ALTER TABLE MODELE_FEUILLE_DOC ADD (NO_FORMULAIRE_ACI NUMBER(5,0));

-- remplissage des valeurs par défaut pour 2016
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 1, 'Déclaration PM', 140, 11110
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT IN ('DECLARATION_IMPOT_PM_BATCH', 'DECLARATION_IMPOT_PM_LOCAL');

INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 2, 'Annexe 01a', 141, 11111
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 3, 'Annexe 01b', 142, 11112
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 4, 'Annexe 01c', 143, 11113
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 5, 'Annexe 01d', 144, 11114
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 6, 'Annexe 01e', 145, 11115
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 7, 'Annexe 02', 146, 11116
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 8, 'Annexe 03', 147, 11117
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 9, 'Annexe 04a', 148, 11118
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 10, 'Annexe 04b', 149, 11119
	FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_PM_LOCAL';

INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 1, 'Déclaration APM', 130, 11121
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT IN ('DECLARATION_IMPOT_APM_BATCH', 'DECLARATION_IMPOT_APM_LOCAL');

INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 2, 'Annexe 01a', 132, 11123
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_APM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 3, 'Annexe 01b', 134, 11125
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_APM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 4, 'Annexe 02', 136, 11127
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_APM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 5, 'Annexe 03a', 137, 11128
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_APM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 6, 'Annexe 03b', 138, 11129
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_APM_LOCAL';
INSERT INTO MODELE_FEUILLE_DOC (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, MODELE_ID, SORT_INDEX, INTITULE_FEUILLE, NO_CADEV, NO_FORMULAIRE_ACI)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', MD.ID, 7, 'Annexe 04', 139, 11130
FROM MODELE_DOCUMENT MD WHERE MD.TYPE_DOCUMENT='DECLARATION_IMPOT_APM_LOCAL';
