-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.3', '6.0.2_6.0.3_upgrade');

-- Changement de classe des déclarations migrées sur les PM
UPDATE DECLARATION DI
SET DI.DOCUMENT_TYPE='DIPM'
WHERE DI.DOCUMENT_TYPE='DI' AND EXISTS(SELECT 1 FROM TIERS T WHERE T.NUMERO=DI.TIERS_ID AND T.TIERS_TYPE='Entreprise');