-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.3', '6.0.2_6.0.3_upgrade');

-- Changement de classe des déclarations migrées sur les PM
UPDATE DECLARATION DI
SET DI.DOCUMENT_TYPE='DIPM'
WHERE DI.DOCUMENT_TYPE='DI' AND EXISTS(SELECT 1 FROM TIERS T WHERE T.NUMERO=DI.TIERS_ID AND T.TIERS_TYPE='Entreprise');

-- Changement de la taille de la colonne DONNEES_RC.FORME_JURIDIQUE (5 -> 15)
ALTER TABLE DONNEES_RC MODIFY FORME_JURIDIQUE NVARCHAR2(15);

-- mapping des formes juridiques migrées jusque là...
UPDATE DONNEES_RC SET FORME_JURIDIQUE='ASSOCIATION' WHERE FORME_JURIDIQUE='ASS';
UPDATE DONNEES_RC SET FORME_JURIDIQUE='CORP_DP_ENT' WHERE FORME_JURIDIQUE='EDP';
UPDATE DONNEES_RC SET FORME_JURIDIQUE='SCOOP' WHERE FORME_JURIDIQUE='COOP';
-- UPDATE DONNEES_RC SET FORME_JURIDIQUE='SARL' WHERE FORME_JURIDIQUE='SARL';
-- UPDATE DONNEES_RC SET FORME_JURIDIQUE='SA' WHERE FORME_JURIDIQUE='SA';
-- UPDATE DONNEES_RC SET FORME_JURIDIQUE='SC' WHERE FORME_JURIDIQUE='SC';
-- UPDATE DONNEES_RC SET FORME_JURIDIQUE='SCA' WHERE FORME_JURIDIQUE='SCA';
UPDATE DONNEES_RC SET FORME_JURIDIQUE='FONDATION' WHERE FORME_JURIDIQUE='FOND';
-- UPDATE DONNEES_RC SET FORME_JURIDIQUE='SNC' WHERE FORME_JURIDIQUE='SNC';
