@startuml 03_unireg_component_diagram_service_infrastructure
!include c4/C4_Container.puml

title Beans Spring du service d'infrastructure

Container_Boundary(uniregWeb, "Unireg Web") {

    Container(webBeanClient, "Some Bean", "Spring Bean", "Client du service d'instrastructure")

    Container(webInfrastructureService, "serviceInfrastructureService", "Spring Bean", "Service d'infrastructure")
	Container(webConnectorCache, "infrastructureConnectorCache", "Spring Bean", "Cache mémoire")
	Container(webConnectorTracing, "infrastructureConnectorTracing", "Spring Bean", "Tracing des appels")
	Container(webConnectorRemote, "infrastructureConnectorRemote", "Spring Bean", "Invoker Spring-remoting")

	Rel_D(webBeanClient, webInfrastructureService, "Utilise")
	Rel_R(webInfrastructureService, webConnectorCache, "Utilise")
	Rel_D(webConnectorCache, webConnectorTracing, "Utilise")
	Rel_L(webConnectorTracing, webConnectorRemote, "Délègue")
}

Container_Boundary(uniregNexus, "Unireg Nexus") {
    Container(nexusConnectorEndPoint, "infrastructureConnectorEndPoint", "Spring Bean", "Statistiques des appels")
	Container(nexusConnectorCache, "infrastructureConnectorCache", "Spring Bean", "Cache mémoire")
	Container(nexusConnectorTracing, "infrastructureConnectorTracing", "Spring Bean", "Tracing des appels")
	Container(nexusConnectorFidor, "infrastructureConnectorFidor", "Spring Bean", "Implémentation Fidor du service")
	Container(fidorClient, "fidorClient", "Spring Bean", "Client Fidor bas-niveau")

	Rel_R(nexusConnectorEndPoint, nexusConnectorCache, "Délègue")
	Rel_D(nexusConnectorCache, nexusConnectorTracing, "Utilise")
	Rel_L(nexusConnectorTracing, nexusConnectorFidor, "Délègue")
	Rel_D(nexusConnectorFidor, fidorClient, "Utilise")
}

Rel_D(webConnectorRemote, nexusConnectorEndPoint, "Appelle", "Spring-remoting/HTTP")

@enduml
