package ch.vd.unireg.interfaces.organisation.rcent.converters;

import org.jetbrains.annotations.NotNull;

import ch.vd.evd0022.v3.TypeOfNotice;
import ch.vd.unireg.type.TypeEvenementOrganisation;

public class TypeOfNoticeConverter extends BaseEnumConverter<TypeOfNotice, TypeEvenementOrganisation> {

	@Override
	@NotNull
	public TypeEvenementOrganisation convert(@NotNull TypeOfNotice value) {
		switch (value) {
		case FOSC_NOUVELLE_ENTREPRISE:
			return TypeEvenementOrganisation.FOSC_NOUVELLE_ENTREPRISE;
		case FOSC_NOUVELLE_SUCCURSALE:
			return TypeEvenementOrganisation.FOSC_NOUVELLE_SUCCURSALE;
		case FOSC_DISSOLUTION_ENTREPRISE:
			return TypeEvenementOrganisation.FOSC_DISSOLUTION_ENTREPRISE;
		case FOSC_RADIATION_ENTREPRISE:
			return TypeEvenementOrganisation.FOSC_RADIATION_ENTREPRISE;
		case FOSC_RADIATION_SUCCURSALE:
			return TypeEvenementOrganisation.FOSC_RADIATION_SUCCURSALE;
		case FOSC_REVOCATION_DISSOLUTION_ENTREPRISE:
			return TypeEvenementOrganisation.FOSC_REVOCATION_DISSOLUTION_ENTREPRISE;
		case FOSC_REINSCRIPTION_ENTREPRISE:
			return TypeEvenementOrganisation.FOSC_REINSCRIPTION_ENTREPRISE;
		case FOSC_AUTRE_MUTATION:
			return TypeEvenementOrganisation.FOSC_AUTRE_MUTATION;
		case IMPORTATION_ENTREPRISE:
			return TypeEvenementOrganisation.IMPORTATION_ENTREPRISE;
		case FOSC_AVIS_PREALABLE_OUVERTURE_FAILLITE:
			return TypeEvenementOrganisation.FOSC_AVIS_PREALABLE_OUVERTURE_FAILLITE;
		case FOSC_PUBLICATION_FAILLITE_ET_APPEL_AUX_CREANCIERS:
			return TypeEvenementOrganisation.FOSC_PUBLICATION_FAILLITE_ET_APPEL_AUX_CREANCIERS;
		case FOSC_SUSPENSION_FAILLITE:
			return TypeEvenementOrganisation.FOSC_SUSPENSION_FAILLITE;
		case FOSC_ETAT_DE_COLLOCATION_ET_INVENTAIRE_DANS_FAILLITE:
			return TypeEvenementOrganisation.FOSC_ETAT_DE_COLLOCATION_ET_INVENTAIRE_DANS_FAILLITE;
		case FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_FAILLITE:
			return TypeEvenementOrganisation.FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_FAILLITE;
		case FOSC_CLOTURE_DE_LA_FAILLITE:
			return TypeEvenementOrganisation.FOSC_CLOTURE_DE_LA_FAILLITE;
		case FOSC_REVOCATION_DE_LA_FAILLITE:
			return TypeEvenementOrganisation.FOSC_REVOCATION_DE_LA_FAILLITE;
		case FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_FAILLITE:
			return TypeEvenementOrganisation.FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_FAILLITE;
		case FOSC_ETAT_DES_CHARGES_DANS_FAILLITE:
			return TypeEvenementOrganisation.FOSC_ETAT_DES_CHARGES_DANS_FAILLITE;
		case FOSC_COMMUNICATION_DANS_FAILLITE:
			return TypeEvenementOrganisation.FOSC_COMMUNICATION_DANS_FAILLITE;
		case FOSC_DEMANDE_SURSIS_CONCORDATAIRE:
			return TypeEvenementOrganisation.FOSC_DEMANDE_SURSIS_CONCORDATAIRE;
		case FOSC_SURSIS_CONCORDATAIRE_PROVISOIRE:
			return TypeEvenementOrganisation.FOSC_SURSIS_CONCORDATAIRE_PROVISOIRE;
		case FOSC_SURSIS_CONCORDATAIRE:
			return TypeEvenementOrganisation.FOSC_SURSIS_CONCORDATAIRE;
		case FOSC_APPEL_AUX_CREANCIERS_DANS_CONCORDAT:
			return TypeEvenementOrganisation.FOSC_APPEL_AUX_CREANCIERS_DANS_CONCORDAT;
		case FOSC_AUDIENCE_DE_LIQUIDATION_PAR_ABANDON_ACTIF:
			return TypeEvenementOrganisation.FOSC_AUDIENCE_DE_LIQUIDATION_PAR_ABANDON_ACTIF;
		case FOSC_PROLONGATION_SURSIS_CONCORDATAIRE:
			return TypeEvenementOrganisation.FOSC_PROLONGATION_SURSIS_CONCORDATAIRE;
		case FOSC_ANNULATION_SURSIS_CONCORDATAIRE:
			return TypeEvenementOrganisation.FOSC_ANNULATION_SURSIS_CONCORDATAIRE;
		case FOSC_CONVOCATION_A_ASSEMBLEE_DES_CREANCIERS:
			return TypeEvenementOrganisation.FOSC_CONVOCATION_A_ASSEMBLEE_DES_CREANCIERS;
		case FOSC_HOMOLOGATION_DU_CONCORDAT:
			return TypeEvenementOrganisation.FOSC_HOMOLOGATION_DU_CONCORDAT;
		case FOSC_REFUS_HOMOLOGATION_DU_CONCORDAT:
			return TypeEvenementOrganisation.FOSC_REFUS_HOMOLOGATION_DU_CONCORDAT;
		case FOSC_REVOCATION_DU_CONCORDAT:
			return TypeEvenementOrganisation.FOSC_REVOCATION_DU_CONCORDAT;
		case FOSC_ETAT_DE_COLLOCATION_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF:
			return TypeEvenementOrganisation.FOSC_ETAT_DE_COLLOCATION_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF;
		case FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF:
			return TypeEvenementOrganisation.FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF;
		case FOSC_CONCORDAT_DE_BANQUE_ET_DE_CAISSE_EPARGNE:
			return TypeEvenementOrganisation.FOSC_CONCORDAT_DE_BANQUE_ET_DE_CAISSE_EPARGNE;
		case FOSC_COMMUNICATION_DANS_LE_CONCORDAT:
			return TypeEvenementOrganisation.FOSC_COMMUNICATION_DANS_LE_CONCORDAT;
		case FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_POURSUITE:
			return TypeEvenementOrganisation.FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_POURSUITE;
		case FOSC_COMMANDEMENT_DE_PAYER:
			return TypeEvenementOrganisation.FOSC_COMMANDEMENT_DE_PAYER;
		case FOSC_PROCES_VERBAL_SEQUESTRE:
			return TypeEvenementOrganisation.FOSC_PROCES_VERBAL_SEQUESTRE;
		case FOSC_PROCES_VERBAL_SAISIE:
			return TypeEvenementOrganisation.FOSC_PROCES_VERBAL_SAISIE;
		case FOSC_COMMUNICATION_DANS_LA_POURSUITE:
			return TypeEvenementOrganisation.FOSC_COMMUNICATION_DANS_LA_POURSUITE;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_FUSION_OU_SCISSION:
			return TypeEvenementOrganisation.FOSC_APPEL_AUX_CREANCIERS_SUITE_FUSION_OU_SCISSION;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_LIQUIDATION:
			return TypeEvenementOrganisation.FOSC_APPEL_AUX_CREANCIERS_SUITE_LIQUIDATION;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_REDUCTION_CAPITAL:
			return TypeEvenementOrganisation.FOSC_APPEL_AUX_CREANCIERS_SUITE_REDUCTION_CAPITAL;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFORMATION_SA_EN_SARL:
			return TypeEvenementOrganisation.FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFORMATION_SA_EN_SARL;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFERT_ETRANGER:
			return TypeEvenementOrganisation.FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFERT_ETRANGER;
		case IDE_NOUVELLE_INSCRIPTION:
			return TypeEvenementOrganisation.IDE_NOUVELLE_INSCRIPTION;
		case IDE_MUTATION:
			return TypeEvenementOrganisation.IDE_MUTATION;
		case IDE_RADIATION:
			return TypeEvenementOrganisation.IDE_RADIATION;
		case IDE_REACTIVATION:
			return TypeEvenementOrganisation.IDE_REACTIVATION;
		case IDE_ANNULATION:
			return TypeEvenementOrganisation.IDE_ANNULATION;
		case RCPERS_DECES:
			return TypeEvenementOrganisation.RCPERS_DECES;
		case RCPERS_ANNULATION_DECES:
			return TypeEvenementOrganisation.RCPERS_ANNULATION_DECES;
		case RCPERS_DEPART:
			return TypeEvenementOrganisation.RCPERS_DEPART;
		case RCPERS_ANNULATION_DEPART:
			return TypeEvenementOrganisation.RCPERS_ANNULATION_DEPART;
		case RCPERS_CORRECTION_DONNEES:
			return TypeEvenementOrganisation.RCPERS_CORRECTION_DONNEES;
		case REE_NOUVELLE_INSCRIPTION:
			return TypeEvenementOrganisation.REE_NOUVELLE_INSCRIPTION;
		case REE_MUTATION:
			return TypeEvenementOrganisation.REE_MUTATION;
		case REE_SUPPRESSION:
			return TypeEvenementOrganisation.REE_SUPPRESSION;
		case REE_RADIATION:
			return TypeEvenementOrganisation.REE_RADIATION;
		case REE_TRANSFERT_ETABLISSEMENT:
			return TypeEvenementOrganisation.REE_TRANSFERT_ETABLISSEMENT;
		case REE_REACTIVATION:
			return TypeEvenementOrganisation.REE_REACTIVATION;
		case REE_NOUVEL_ETABLISSEMENT:
			return TypeEvenementOrganisation.REE_NOUVEL_ETABLISSEMENT;
		default:
			throw new IllegalArgumentException(genericUnsupportedValueMessage(value));
		}
	}
}
