package ch.vd.uniregctb.rf;

public enum TypeMutation {
	ACHAT,
	AUGMENTATION,
	CESSION,
	CONSTITUTION_PPE,
	CONSTITUTION_PARTS_PROPRIETE,
	DIVISION_BIEN_FONDS,
	DONATION,
	DELIVRANCE_LEGS,
	ECHANGE,
	GROUPEMENT_BIEN_FONDS,
	JUGEMENT,
	PARTAGE,
	REMANIEMENT_PARCELLAIRE,
	REALISATION_FORCEE,
	SUCCESSION,
	TRANSFERT,
	FIN_DE_PROPRIETE
}
