package ch.vd.unireg.interfaces.entreprise.rcent.converters;

import org.jetbrains.annotations.NotNull;

import ch.vd.evd0022.v3.TypeOfBusinessPublication;
import ch.vd.unireg.interfaces.entreprise.data.TypeDePublicationBusiness;

public class TypeOfBusinessPublicationConverter extends BaseEnumConverter<TypeOfBusinessPublication, TypeDePublicationBusiness> {

	@Override
	@NotNull
	protected TypeDePublicationBusiness convert(@NotNull TypeOfBusinessPublication value) {
		switch (value) {
		case FOSC_AVIS_PREALABLE_OUVERTURE_FAILLITE:
			return TypeDePublicationBusiness.FOSC_AVIS_PREALABLE_OUVERTURE_FAILLITE;
		case FOSC_PUBLICATION_FAILLITE_ET_APPEL_AUX_CREANCIERS:
			return TypeDePublicationBusiness.FOSC_PUBLICATION_FAILLITE_ET_APPEL_AUX_CREANCIERS;
		case FOSC_SUSPENSION_FAILLITE:
			return TypeDePublicationBusiness.FOSC_SUSPENSION_FAILLITE;
		case FOSC_ETAT_DE_COLLOCATION_ET_INVENTAIRE_DANS_FAILLITE:
			return TypeDePublicationBusiness.FOSC_ETAT_DE_COLLOCATION_ET_INVENTAIRE_DANS_FAILLITE;
		case FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_FAILLITE:
			return TypeDePublicationBusiness.FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_FAILLITE;
		case FOSC_CLOTURE_DE_LA_FAILLITE:
			return TypeDePublicationBusiness.FOSC_CLOTURE_DE_LA_FAILLITE;
		case FOSC_REVOCATION_DE_LA_FAILLITE:
			return TypeDePublicationBusiness.FOSC_REVOCATION_DE_LA_FAILLITE;
		case FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_FAILLITE:
			return TypeDePublicationBusiness.FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_FAILLITE;
		case FOSC_ETAT_DES_CHARGES_DANS_FAILLITE:
			return TypeDePublicationBusiness.FOSC_ETAT_DES_CHARGES_DANS_FAILLITE;
		case FOSC_COMMUNICATION_DANS_FAILLITE:
			return TypeDePublicationBusiness.FOSC_COMMUNICATION_DANS_FAILLITE;
		case FOSC_DEMANDE_SURSIS_CONCORDATAIRE:
			return TypeDePublicationBusiness.FOSC_DEMANDE_SURSIS_CONCORDATAIRE;
		case FOSC_SURSIS_CONCORDATAIRE_PROVISOIRE:
			return TypeDePublicationBusiness.FOSC_SURSIS_CONCORDATAIRE_PROVISOIRE;
		case FOSC_SURSIS_CONCORDATAIRE:
			return TypeDePublicationBusiness.FOSC_SURSIS_CONCORDATAIRE;
		case FOSC_APPEL_AUX_CREANCIERS_DANS_CONCORDAT:
			return TypeDePublicationBusiness.FOSC_APPEL_AUX_CREANCIERS_DANS_CONCORDAT;
		case FOSC_AUDIENCE_DE_LIQUIDATION_PAR_ABANDON_ACTIF:
			return TypeDePublicationBusiness.FOSC_AUDIENCE_DE_LIQUIDATION_PAR_ABANDON_ACTIF;
		case FOSC_PROLONGATION_SURSIS_CONCORDATAIRE:
			return TypeDePublicationBusiness.FOSC_PROLONGATION_SURSIS_CONCORDATAIRE;
		case FOSC_ANNULATION_SURSIS_CONCORDATAIRE:
			return TypeDePublicationBusiness.FOSC_ANNULATION_SURSIS_CONCORDATAIRE;
		case FOSC_CONVOCATION_A_ASSEMBLEE_DES_CREANCIERS:
			return TypeDePublicationBusiness.FOSC_CONVOCATION_A_ASSEMBLEE_DES_CREANCIERS;
		case FOSC_HOMOLOGATION_DU_CONCORDAT:
			return TypeDePublicationBusiness.FOSC_HOMOLOGATION_DU_CONCORDAT;
		case FOSC_REFUS_HOMOLOGATION_DU_CONCORDAT:
			return TypeDePublicationBusiness.FOSC_REFUS_HOMOLOGATION_DU_CONCORDAT;
		case FOSC_REVOCATION_DU_CONCORDAT:
			return TypeDePublicationBusiness.FOSC_REVOCATION_DU_CONCORDAT;
		case FOSC_ETAT_DE_COLLOCATION_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF:
			return TypeDePublicationBusiness.FOSC_ETAT_DE_COLLOCATION_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF;
		case FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF:
			return TypeDePublicationBusiness.FOSC_TABLEAU_DE_DISTRIBUTION_ET_DECOMPTE_FINAL_DANS_CONCORDAT_PAR_ABANDON_D_ACTIF;
		case FOSC_CONCORDAT_DE_BANQUE_ET_DE_CAISSE_EPARGNE:
			return TypeDePublicationBusiness.FOSC_CONCORDAT_DE_BANQUE_ET_DE_CAISSE_EPARGNE;
		case FOSC_COMMUNICATION_DANS_LE_CONCORDAT:
			return TypeDePublicationBusiness.FOSC_COMMUNICATION_DANS_LE_CONCORDAT;
		case FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_POURSUITE:
			return TypeDePublicationBusiness.FOSC_VENTE_AUX_ENCHERES_FORCEE_IMMEUBLES_DANS_POURSUITE;
		case FOSC_COMMANDEMENT_DE_PAYER:
			return TypeDePublicationBusiness.FOSC_COMMANDEMENT_DE_PAYER;
		case FOSC_PROCES_VERBAL_SEQUESTRE:
			return TypeDePublicationBusiness.FOSC_PROCES_VERBAL_SEQUESTRE;
		case FOSC_PROCES_VERBAL_SAISIE:
			return TypeDePublicationBusiness.FOSC_PROCES_VERBAL_SAISIE;
		case FOSC_COMMUNICATION_DANS_LA_PROUSUITE:
			return TypeDePublicationBusiness.FOSC_COMMUNICATION_DANS_LA_PROUSUITE;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_FUSION_OU_SCISSION:
			return TypeDePublicationBusiness.FOSC_APPEL_AUX_CREANCIERS_SUITE_FUSION_OU_SCISSION;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_LIQUIDATION:
			return TypeDePublicationBusiness.FOSC_APPEL_AUX_CREANCIERS_SUITE_LIQUIDATION;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_REDUCTION_CAPITAL:
			return TypeDePublicationBusiness.FOSC_APPEL_AUX_CREANCIERS_SUITE_REDUCTION_CAPITAL;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFORMATION_SA_EN_SARL:
			return TypeDePublicationBusiness.FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFORMATION_SA_EN_SARL;
		case FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFERT_ETRANGER:
			return TypeDePublicationBusiness.FOSC_APPEL_AUX_CREANCIERS_SUITE_TRANSFERT_ETRANGER;
		default:
			throw new IllegalArgumentException(genericUnsupportedValueMessage(value));
		}
	}
}
