-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.3.1', '7.3.0_7.3.1_upgrade');

-- SIFISC-24595 : ajout des principaux de communautés
create table MODELE_COMMUNAUTE_RF
(
    ID NUMBER(19) not null
        primary key,
    ANNULATION_DATE TIMESTAMP(6),
    ANNULATION_USER NVARCHAR2(65),
    LOG_CDATE TIMESTAMP(6),
    LOG_CUSER NVARCHAR2(65),
    LOG_MDATE TIMESTAMP(6),
    LOG_MUSER NVARCHAR2(65),
    MEMBRES_HASH_CODE NUMBER(10)
);
create index IDX_MODCOMM_HASHCODE on MODELE_COMMUNAUTE_RF (MEMBRES_HASH_CODE);

create table MEMBRE_COMMUNAUTE_RF
(
    MODEL_COMMUNAUTE_ID NUMBER(19) not null
        constraint FK_MEMCOMM_MODEL_ID
        references MODELE_COMMUNAUTE_RF,
    AYANT_DROIT_ID NUMBER(19) not null
        constraint FK_MEMCOMM_AYANTDROIT_ID
        references RF_AYANT_DROIT,
    primary key (MODEL_COMMUNAUTE_ID, AYANT_DROIT_ID)
);

create table PRINCIPAL_COMMUNAUTE_RF
(
    ID NUMBER(19) not null
        primary key,
    ANNULATION_DATE TIMESTAMP(6),
    ANNULATION_USER NVARCHAR2(65),
    LOG_CDATE TIMESTAMP(6),
    LOG_CUSER NVARCHAR2(65),
    LOG_MDATE TIMESTAMP(6),
    LOG_MUSER NVARCHAR2(65),
    DATE_DEBUT NUMBER(10),
    DATE_FIN NUMBER(10),
    PRINCIPAL_ID NUMBER(19) not null
        constraint FK_PRINCIPAL_ID
        references RF_AYANT_DROIT,
    MODEL_COMMUNAUTE_ID NUMBER(19) not null
        constraint FK_PRINC_MODCOMM_ID
        references MODELE_COMMUNAUTE_RF
);
create index IDX_PRINC_PRINCIPAL_ID on PRINCIPAL_COMMUNAUTE_RF (PRINCIPAL_ID);
create index IDX_PRINC_MODCOMM_ID on PRINCIPAL_COMMUNAUTE_RF (MODEL_COMMUNAUTE_ID);

create table REGROUPEMENT_COMMUNAUTE_RF
(
    ID NUMBER(19) not null
        primary key,
    ANNULATION_DATE TIMESTAMP(6),
    ANNULATION_USER NVARCHAR2(65),
    LOG_CDATE TIMESTAMP(6),
    LOG_CUSER NVARCHAR2(65),
    LOG_MDATE TIMESTAMP(6),
    LOG_MUSER NVARCHAR2(65),
    DATE_DEBUT NUMBER(10),
    DATE_FIN NUMBER(10),
    COMMUNAUTE_ID NUMBER(19) not null
        constraint FK_REGRCOMM_RF_COMMUNAUTE_ID
        references RF_AYANT_DROIT,
    MODEL_ID NUMBER(19) not null
        constraint FK_REGRCOMM_RF_MODEL_ID
        references MODELE_COMMUNAUTE_RF
);
create index IDX_REGRCOMM_RF_COMMUNAUTE_ID on REGROUPEMENT_COMMUNAUTE_RF (COMMUNAUTE_ID);
create index IDX_REGRCOMM_RF_MODEL_ID on REGROUPEMENT_COMMUNAUTE_RF (MODEL_ID);


