-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.3.0', '7.2.3bis_7.3.0_upgrade');

-- SIFISC-24752 : augmenté les valeurs maximales sur les données des allégements fiscaux
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_REVENU NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_VOLUME NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_SURFACE NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_REVENU NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_VOLUME NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_SURFACE NUMBER(19);

-- SIFISC-21866 Cycle de vie des autres documents fiscaux comme les DI (Unification DI - Autres documents)
ALTER TABLE DECLARATION RENAME TO DOCUMENT_FISCAL;
ALTER TABLE DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_TRS_ID;
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_TRS_ID FOREIGN KEY (TIERS_ID) REFERENCES TIERS;
ALTER TABLE DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_DOC_ID;
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_MODOC_ID FOREIGN KEY (MODELE_DOC_ID) REFERENCES MODELE_DOCUMENT;
ALTER TABLE DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_PF_ID;
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_PF_ID FOREIGN KEY (PERIODE_ID) REFERENCES PERIODE_FISCALE;
ALTER Table DOCUMENT_FISCAL MODIFY DATE_DEBUT NULL;
ALTER Table DOCUMENT_FISCAL MODIFY DATE_FIN NULL;
ALTER Table DOCUMENT_FISCAL MODIFY PERIODE_ID NULL;
ALTER INDEX IDX_DECL_TRS_ID RENAME TO IDX_DOCFISC_TRS_ID;
ALTER INDEX IDX_SFZ RENAME TO IDX_DOCFISC_TYPE_ANNUL_DATE;

ALTER TABLE DELAI_DECLARATION RENAME TO DELAI_DOCUMENT_FISCAL;
ALTER TABLE DELAI_DOCUMENT_FISCAL ADD DELAI_TYPE nvarchar2(31);
UPDATE DELAI_DOCUMENT_FISCAL SET DELAI_TYPE = 'DELAI_DECLARATION' WHERE DELAI_TYPE IS NULL;
ALTER TABLE DELAI_DOCUMENT_FISCAL MODIFY DELAI_TYPE NOT NULL;
ALTER TABLE DELAI_DOCUMENT_FISCAL RENAME COLUMN DECLARATION_ID TO DOCUMENT_FISCAL_ID;
ALTER TABLE DELAI_DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_DEL_DI_ID;
ALTER TABLE DELAI_DOCUMENT_FISCAL ADD CONSTRAINT FK_DEL_DOCFISC_DOCFISC_ID FOREIGN KEY (DOCUMENT_FISCAL_ID) REFERENCES DOCUMENT_FISCAL;
ALTER INDEX IDX_DE_DI_DI_ID RENAME TO IDX_DEL_DOCFISC_DOCFISC_ID;

ALTER TABLE ETAT_DECLARATION RENAME TO ETAT_DOCUMENT_FISCAL;
ALTER TABLE ETAT_DOCUMENT_FISCAL ADD ETAT_TYPE nvarchar2(31);
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_EMISE', TYPE = 'EMIS' WHERE TYPE = 'EMISE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_SOMMEE', TYPE = 'SOMME' WHERE TYPE = 'SOMMEE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_RAPPELEE', TYPE = 'RAPPELE' WHERE TYPE = 'RAPPELEE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_ECHUE', TYPE = 'ECHU' WHERE TYPE = 'ECHUE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_SUSPENDUE', TYPE = 'SUSPENDU' WHERE TYPE = 'SUSPENDUE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_RETOURNEE', TYPE = 'RETOURNE' WHERE TYPE = 'RETOURNEE';
ALTER TABLE ETAT_DOCUMENT_FISCAL RENAME COLUMN DECLARATION_ID TO DOCUMENT_FISCAL_ID;
ALTER TABLE ETAT_DOCUMENT_FISCAL DROP CONSTRAINT FK_ET_DI_DI_ID;
ALTER TABLE ETAT_DOCUMENT_FISCAL ADD CONSTRAINT FK_ET_DOCFISC_DOCFISC_ID FOREIGN KEY (DOCUMENT_FISCAL_ID) REFERENCES DOCUMENT_FISCAL;
ALTER INDEX IDX_ET_DI_DI_ID RENAME TO IDX_ET_DOCFISC_DOCFISC_ID;
ALTER INDEX IDX_ED_LOG_MDATE RENAME TO IDX_ET_DOCFISC_LOG_MDATE;
ALTER INDEX IDX_ET_DI_SOMM_DI RENAME TO IDX_ET_DOCFISC_SOMM_DOCFISC;

ALTER TABLE EVENEMENT_FISCAL DROP CONSTRAINT FK_EVTFISC_DECL_ID;
ALTER TABLE EVENEMENT_FISCAL ADD CONSTRAINT FK_EVTFISC_DOCFISC_ID FOREIGN KEY (DECLARATION_ID) REFERENCES DOCUMENT_FISCAL;
