-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.3.0', '7.2.3bis_7.3.0_upgrade');

-- SIFISC-24752 : augmenté les valeurs maximales sur les données des allégements fiscaux
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_REVENU NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_VOLUME NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_SURFACE NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_REVENU NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_VOLUME NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_SURFACE NUMBER(19);

-- SIFISC-21866 Cycle de vie des autres documents fiscaux comme les DI.
ALTER TABLE DECLARATION MODIFY CONSTRAINT FK_DECL_TRS_ID RENAME TO FK_DOCFISC_TRS_ID;
ALTER TABLE DECLARATION MODIFY CONSTRAINT FK_DECL_DOC_ID RENAME TO FK_DOCFISC_DOC_ID;
ALTER TABLE DECLARATION MODIFY CONSTRAINT FK_DECL_PF_ID RENAME TO FK_DOCFISC_PF_ID;
ALTER TABLE DECLARATION RENAME TO DOCUMENT_FISCAL;
ALTER INDEX IDX_DECL_TRS_ID RENAME TO IDX_DOCFISC_TRS_ID;

ALTER TABLE DELAI_DECLARATION RENAME COLUMN DECLARATION_ID TO DOCUMENT_FISCAL_ID;
ALTER TABLE DELAI_DECLARATION MODIFY CONSTRAINT FK_DECL_DEL_DI_ID RENAME TO FK_DOCFISC_DEL_DOCFISC_ID;
ALTER TABLE DELAI_DECLARATION RENAME TO DELAI_DOCUMENT_FISCAL;
ALTER INDEX IDX_DE_DI_DI_ID RENAME TO IDX_DE_DOCFISC_DOCFISC_ID;

ALTER TABLE ETAT_DECLARATION RENAME COLUMN DECLARATION_ID TO DOCUMENT_FISCAL_ID;
ALTER TABLE ETAT_DECLARATION MODIFY CONSTRAINT FK_ET_DI_DI_ID RENAME TO FK_ET_DOCFISC_DOCFISC_ID;
ALTER TABLE ETAT_DECLARATION RENAME TO ETAT_DOCUMENT_FISCAL;
ALTER INDEX IDX_ET_DI_DI_ID RENAME TO IDX_ET_DOCFISC_DOCFISC_ID;

ALTER TABLE EVENEMENT_FISCAL MODIFY CONSTRAINT FK_EVTFISC_DECL_ID RENAME TO FK_EVTFISC_DOCFISC_ID
