-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.3.0', '7.2.3bis_7.3.0_upgrade');

-- SIFISC-24752 : augmenté les valeurs maximales sur les données des allégements fiscaux
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_REVENU NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_VOLUME NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_LOC_SURFACE NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_REVENU NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_VOLUME NUMBER(19);
ALTER TABLE ALLEGEMENT_FONCIER MODIFY DEG_PRUS_SURFACE NUMBER(19);

-- SIFISC-21866 Cycle de vie des autres documents fiscaux comme les DI (Unification DI - Autres documents)
ALTER TABLE DECLARATION RENAME TO DOCUMENT_FISCAL;
ALTER TABLE DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_TRS_ID;
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_TRS_ID FOREIGN KEY (TIERS_ID) REFERENCES TIERS;
ALTER TABLE DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_DOC_ID;
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_MODOC_ID FOREIGN KEY (MODELE_DOC_ID) REFERENCES MODELE_DOCUMENT;
ALTER TABLE DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_PF_ID;
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_PF_ID FOREIGN KEY (PERIODE_ID) REFERENCES PERIODE_FISCALE;
ALTER TABLE DOCUMENT_FISCAL MODIFY DATE_DEBUT NULL;
ALTER TABLE DOCUMENT_FISCAL MODIFY DATE_FIN NULL;
ALTER TABLE DOCUMENT_FISCAL MODIFY PERIODE_ID NULL;
DROP INDEX IDX_DECL_TRS_ID;
DROP INDEX IDX_SFZ;

ALTER TABLE DELAI_DECLARATION RENAME TO DELAI_DOCUMENT_FISCAL;
DROP INDEX IDX_DE_DI_DI_ID;
ALTER TABLE DELAI_DOCUMENT_FISCAL ADD DELAI_TYPE NVARCHAR2(31);
UPDATE DELAI_DOCUMENT_FISCAL SET DELAI_TYPE = 'DELAI_DECLARATION' WHERE DELAI_TYPE IS NULL;
ALTER TABLE DELAI_DOCUMENT_FISCAL MODIFY DELAI_TYPE NOT NULL;
ALTER TABLE DELAI_DOCUMENT_FISCAL RENAME COLUMN DECLARATION_ID TO DOCUMENT_FISCAL_ID;
ALTER TABLE DELAI_DOCUMENT_FISCAL DROP CONSTRAINT FK_DECL_DEL_DI_ID;
ALTER TABLE DELAI_DOCUMENT_FISCAL ADD CONSTRAINT FK_DEL_DOCFISC_DOCFISC_ID FOREIGN KEY (DOCUMENT_FISCAL_ID) REFERENCES DOCUMENT_FISCAL;

ALTER TABLE ETAT_DECLARATION RENAME TO ETAT_DOCUMENT_FISCAL;
DROP INDEX IDX_ET_DI_DI_ID;
DROP INDEX IDX_ED_LOG_MDATE;
DROP INDEX IDX_ET_DI_SOMM_DI;
ALTER TABLE ETAT_DOCUMENT_FISCAL ADD ETAT_TYPE NVARCHAR2(31);
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_EMISE', TYPE = 'EMIS' WHERE TYPE = 'EMISE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_SOMMEE', TYPE = 'SOMME' WHERE TYPE = 'SOMMEE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_RAPPELEE', TYPE = 'RAPPELE' WHERE TYPE = 'RAPPELEE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_ECHUE', TYPE = 'ECHU' WHERE TYPE = 'ECHUE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_SUSPENDUE', TYPE = 'SUSPENDU' WHERE TYPE = 'SUSPENDUE';
UPDATE ETAT_DOCUMENT_FISCAL SET ETAT_TYPE = 'DI_RETOURNEE', TYPE = 'RETOURNE' WHERE TYPE = 'RETOURNEE';
ALTER TABLE ETAT_DOCUMENT_FISCAL RENAME COLUMN DECLARATION_ID TO DOCUMENT_FISCAL_ID;
ALTER TABLE ETAT_DOCUMENT_FISCAL DROP CONSTRAINT FK_ET_DI_DI_ID;
ALTER TABLE ETAT_DOCUMENT_FISCAL ADD CONSTRAINT FK_ET_DOCFISC_DOCFISC_ID FOREIGN KEY (DOCUMENT_FISCAL_ID) REFERENCES DOCUMENT_FISCAL;
ALTER TABLE ETAT_DOCUMENT_FISCAL MODIFY DATE_OBTENTION NOT NULL;

ALTER TABLE EVENEMENT_FISCAL DROP CONSTRAINT FK_EVTFISC_DECL_ID;
ALTER TABLE EVENEMENT_FISCAL ADD CONSTRAINT FK_EVTFISC_DOCFISC_ID FOREIGN KEY (DECLARATION_ID) REFERENCES DOCUMENT_FISCAL;

-- Migration des autres documents fiscaux
ALTER TABLE DOCUMENT_FISCAL ADD LB_TYPE NVARCHAR2(20);
ALTER TABLE DOCUMENT_FISCAL ADD AR_DATE_DEMANDE NUMBER(10,0);
ALTER TABLE DOCUMENT_FISCAL ADD DBF_PERIODE_FISCALE NUMBER(10,0);
ALTER TABLE DOCUMENT_FISCAL ADD DBF_DATE_REQ_RADIATION NUMBER(10,0);
ALTER TABLE DOCUMENT_FISCAL ADD DD_PERIODE_FISCALE NUMBER(10);
ALTER TABLE DOCUMENT_FISCAL ADD DD_IMMEUBLE_ID NUMBER(19);
ALTER TABLE DOCUMENT_FISCAL ADD DD_NUMERO_SEQUENCE NUMBER(10);
ALTER TABLE DOCUMENT_FISCAL ADD DD_CODE_CONTROLE NVARCHAR2(6);
ALTER TABLE DOCUMENT_FISCAL ADD CONSTRAINT FK_DOCFISC_DD_RF_IMMEUBLE_ID FOREIGN KEY (DD_IMMEUBLE_ID) REFERENCES RF_IMMEUBLE;

ALTER TABLE ETAT_DOCUMENT_FISCAL ADD CLE_ARCHIVAGE NVARCHAR2(40);

-- Migrer à proprement parler
-- Migrer les autres documents fiscaux
INSERT INTO DOCUMENT_FISCAL (ID, DOCUMENT_TYPE, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, TIERS_ID, LB_TYPE, AR_DATE_DEMANDE, DBF_DATE_REQ_RADIATION, DBF_PERIODE_FISCALE, DD_CODE_CONTROLE, DD_NUMERO_SEQUENCE, DD_PERIODE_FISCALE, DD_IMMEUBLE_ID)
		SELECT ID, DOC_TYPE, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_CDATE, LOG_CUSER, ENTREPRISE_ID, LB_TYPE, AR_DATE_DEMANDE, DBF_DATE_REQ_RADIATION, DBF_PERIODE_FISCALE, DD_CODE_CONTROLE, DD_NUMERO_SEQUENCE, DD_PERIODE_FISCALE, DD_IMMEUBLE_ID
			FROM AUTRE_DOCUMENT_FISCAL;

-- Générer les états des documents migrés
INSERT INTO ETAT_DOCUMENT_FISCAL (ID, ETAT_TYPE, TYPE, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DATE_OBTENTION, DOCUMENT_FISCAL_ID, DATE_ENVOI_COURRIER, SOURCE, EMOLUMENT, CLE_ARCHIVAGE, CLE_DOCUMENT)
		SELECT HIBERNATE_SEQUENCE.nextval, 'AUTRE_EMIS', 'EMIS', ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_CDATE, LOG_CUSER, DATE_ENVOI, ID, NULL, NULL, NULL, CLE_ARCHIVAGE, CLE_DOCUMENT
			FROM AUTRE_DOCUMENT_FISCAL;
INSERT INTO ETAT_DOCUMENT_FISCAL (ID, ETAT_TYPE, TYPE, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DATE_OBTENTION, DOCUMENT_FISCAL_ID, DATE_ENVOI_COURRIER, SOURCE, EMOLUMENT, CLE_ARCHIVAGE, CLE_DOCUMENT)
		SELECT HIBERNATE_SEQUENCE.nextval, 'AUTRE_RAPPELE', 'RAPPELE', ANNULATION_DATE, ANNULATION_USER, TO_DATE(DATE_RAPPEL, 'YYYYMMDD'), LOG_MUSER, TO_DATE(DATE_RAPPEL, 'YYYYMMDD'), LOG_MUSER, DATE_RAPPEL, ID, NULL, NULL, NULL, CLE_ARCHIVAGE_RAPPEL, CLE_DOCUMENT_RAPPEL
			FROM AUTRE_DOCUMENT_FISCAL
			WHERE DATE_RAPPEL IS NOT NULL;
INSERT INTO ETAT_DOCUMENT_FISCAL (ID, ETAT_TYPE, TYPE, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DATE_OBTENTION, DOCUMENT_FISCAL_ID, DATE_ENVOI_COURRIER, SOURCE, EMOLUMENT, CLE_ARCHIVAGE, CLE_DOCUMENT)
		SELECT HIBERNATE_SEQUENCE.nextval, 'AUTRE_RETOURNE', 'RETOURNE', ANNULATION_DATE, ANNULATION_USER, LOG_MDATE, LOG_MUSER, LOG_MDATE, LOG_MUSER, DATE_RETOUR, ID, NULL, NULL, NULL, NULL, NULL
			FROM AUTRE_DOCUMENT_FISCAL
			WHERE DATE_RETOUR IS NOT NULL;

-- Générer le délai pour les documents concernés
INSERT INTO DELAI_DOCUMENT_FISCAL (ID, DELAI_TYPE, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DOCUMENT_FISCAL_ID, DATE_DEMANDE, DATE_TRAITEMENT, DELAI_ACCORDE_AU, ETAT, SURSIS, CLE_ARCHIVAGE_COURRIER, CLE_DOCUMENT)
	SELECT HIBERNATE_SEQUENCE.nextval, 'DELAI_AUTRE_DOCUMENT_FISCAL', ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, ID, DATE_ENVOI, DATE_ENVOI, DELAI_RETOUR, 'ACCORDE', 0, NULL, NULL
	FROM AUTRE_DOCUMENT_FISCAL
	WHERE DELAI_RETOUR IS NOT NULL;

CREATE INDEX IDX_DOCFISC_TRS_ID on DOCUMENT_FISCAL (TIERS_ID);
CREATE INDEX IDX_DOCFISC_TYPE_ANNUL_DATE ON DOCUMENT_FISCAL(ANNULATION_DATE, DOCUMENT_TYPE);
CREATE INDEX IDX_DOCFISC_DD_RF_IMMEUBLE_ID ON DOCUMENT_FISCAL (DD_IMMEUBLE_ID);

CREATE INDEX IDX_ET_DOCFISC_DOCFISC_ID ON ETAT_DOCUMENT_FISCAL(DOCUMENT_FISCAL_ID);
CREATE INDEX IDX_ET_DOCFISC_LOG_MDATE ON ETAT_DOCUMENT_FISCAL(LOG_MDATE);
CREATE INDEX IDX_ET_DOCFISC_SOMMATION ON ETAT_DOCUMENT_FISCAL(DOCUMENT_FISCAL_ID, ANNULATION_DATE, TYPE, DATE_OBTENTION);

CREATE INDEX IDX_DEL_DOCFISC_DOCFISC_ID ON DELAI_DOCUMENT_FISCAL (DOCUMENT_FISCAL_ID);

-- Renommage de l'ancienne table.
DROP INDEX IDX_DD_RF_IMMEUBLE_ID;
ALTER TABLE AUTRE_DOCUMENT_FISCAL RENAME TO AUTRE_DOCUMENT_FISCAL_MIGREE;