-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('4.12.1', '4.12.0_4.12.1_upgrade');

--
-- [SIFISC-1933] Ajout de l'identifiant district Fiscal et de l'identifiant Region Fiscal pour un TIERS
--
ALTER TABLE TIERS ADD (DISTRICT_FISCAL_ID number(19,0));

ALTER TABLE TIERS ADD (REGION_FISCALE_ID number(19,0));


--
-- [SIFISC-1965] Chargement des codes district et région pour les collectivitées administratives.
--
--Aigle
UPDATE TIERS SET DISTRICT_FISCAL_ID = 1, REGION_FISCALE_ID = null WHERE NUMERO_CA = 1;
--Echallens
UPDATE TIERS SET DISTRICT_FISCAL_ID = 2, REGION_FISCALE_ID = null WHERE NUMERO_CA = 5;
--Grandson
UPDATE TIERS SET DISTRICT_FISCAL_ID = 3, REGION_FISCALE_ID = null WHERE NUMERO_CA = 6;
--Lausanne
UPDATE TIERS SET DISTRICT_FISCAL_ID = 4, REGION_FISCALE_ID = 1 WHERE NUMERO_CA = 7;
--La Vallée
UPDATE TIERS SET DISTRICT_FISCAL_ID = 5, REGION_FISCALE_ID = null WHERE NUMERO_CA = 8;
--Lavaux
UPDATE TIERS SET DISTRICT_FISCAL_ID = 6, REGION_FISCALE_ID = null WHERE NUMERO_CA = 9;
--Morges
UPDATE TIERS SET DISTRICT_FISCAL_ID = 7, REGION_FISCALE_ID = null WHERE NUMERO_CA = 10;
--Moudon
UPDATE TIERS SET DISTRICT_FISCAL_ID = 8, REGION_FISCALE_ID = null WHERE NUMERO_CA = 11;
--Nyon
UPDATE TIERS SET DISTRICT_FISCAL_ID = 9, REGION_FISCALE_ID = 2 WHERE NUMERO_CA = 12;
--Orbe
UPDATE TIERS SET DISTRICT_FISCAL_ID = 10, REGION_FISCALE_ID = null WHERE NUMERO_CA = 13;
--Payerne
UPDATE TIERS SET DISTRICT_FISCAL_ID = 11, REGION_FISCALE_ID = null WHERE NUMERO_CA = 15;
--Pays d'Enhaut
UPDATE TIERS SET DISTRICT_FISCAL_ID = 12, REGION_FISCALE_ID = null WHERE NUMERO_CA = 16;
--Rolle-Aubonne
UPDATE TIERS SET DISTRICT_FISCAL_ID = 13, REGION_FISCALE_ID = null WHERE NUMERO_CA = 17;
--Vevey
UPDATE TIERS SET DISTRICT_FISCAL_ID = 14, REGION_FISCALE_ID = 3 WHERE NUMERO_CA = 18;
--Yverson
UPDATE TIERS SET DISTRICT_FISCAL_ID = 15, REGION_FISCALE_ID = 4 WHERE NUMERO_CA = 19;




