-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.7', '6.0.6_6.0.7_upgrade');

-- allongement de la taille de la colonne 20 -> 31
ALTER TABLE FLAG_ENTREPRISE MODIFY FLAG NVARCHAR2(31);

-- événement fiscal autour de la gestion des flags entreprise
ALTER TABLE EVENEMENT_FISCAL ADD (FLAG_ENTREPRISE_ID NUMBER(19,0), TYPE_EVT_FLAG NVARCHAR2(15));
ALTER TABLE EVENEMENT_FISCAL ADD CONSTRAINT FK_EVTFISC_FLAG_ID FOREIGN KEY (FLAG_ENTREPRISE_ID) REFERENCES FLAG_ENTREPRISE;
