-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.7', '6.0.6_6.0.7_upgrade');

-- allongement de la taille de la colonne 20 -> 31
ALTER TABLE FLAG_ENTREPRISE MODIFY FLAG NVARCHAR2(31);

-- événement fiscal autour de la gestion des flags entreprise
ALTER TABLE EVENEMENT_FISCAL ADD (FLAG_ENTREPRISE_ID NUMBER(19,0), TYPE_EVT_FLAG NVARCHAR2(15));
ALTER TABLE EVENEMENT_FISCAL ADD CONSTRAINT FK_EVTFISC_FLAG_ID FOREIGN KEY (FLAG_ENTREPRISE_ID) REFERENCES FLAG_ENTREPRISE;

--
-- Les 'Données RC' et les capitaux vont être regroupés dans trois entités distinctes de la même table
--
CREATE TABLE DONNEE_CIVILE_ENTREPRISE (
	ID NUMBER(19,0) NOT NULL,
	ANNULATION_DATE TIMESTAMP,
	ANNULATION_USER NVARCHAR2(65),
	LOG_CDATE TIMESTAMP,
	LOG_CUSER NVARCHAR2(65),
	LOG_MDATE TIMESTAMP,
	LOG_MUSER NVARCHAR2(65),
	DONNEE_TYPE NVARCHAR2(20) NOT NULL,
	DATE_DEBUT NUMBER(10, 0) NOT NULL,
	DATE_FIN NUMBER(10, 0),
	RS_RAISON_SOCIALE NVARCHAR2(250),
	FJ_FORME_JURIDIQUE NVARCHAR2(15),
	CAP_MONTANT NUMBER(19,0),
	CAP_MONNAIE NVARCHAR2(3),
	ENTREPRISE_ID NUMBER(19, 0) NOT NULL,
	PRIMARY KEY (ID)
);
ALTER TABLE DONNEE_CIVILE_ENTREPRISE ADD CONSTRAINT FK_DONCIV_ENTRP_ID FOREIGN KEY (ENTREPRISE_ID) REFERENCES TIERS;
CREATE INDEX IDX_DONCIV_ENTRP_ID ON DONNEE_CIVILE_ENTREPRISE (ENTREPRISE_ID ASC, DATE_DEBUT ASC, DONNEE_TYPE ASC);
INSERT INTO DONNEE_CIVILE_ENTREPRISE (ID, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DONNEE_TYPE, DATE_DEBUT, DATE_FIN, RS_RAISON_SOCIALE, ENTREPRISE_ID)
		SELECT HIBERNATE_SEQUENCE.NEXTVAL, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, 'RaisonSociale', DATE_DEBUT, DATE_FIN, RAISON_SOCIALE, ENTREPRISE_ID
		FROM DONNEES_RC;
INSERT INTO DONNEE_CIVILE_ENTREPRISE (ID, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DONNEE_TYPE, DATE_DEBUT, DATE_FIN, FJ_FORME_JURIDIQUE, ENTREPRISE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, 'FormeJuridique', DATE_DEBUT, DATE_FIN, FORME_JURIDIQUE, ENTREPRISE_ID
	FROM DONNEES_RC;
INSERT INTO DONNEE_CIVILE_ENTREPRISE (ID, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DONNEE_TYPE, DATE_DEBUT, DATE_FIN, CAP_MONTANT, CAP_MONNAIE, ENTREPRISE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, 'Capital', DATE_DEBUT, DATE_FIN, MONTANT, MONNAIE, ENTREPRISE_ID
	FROM CAPITAL_ENTREPRISE;
DROP TABLE DONNEES_RC PURGE;
DROP TABLE CAPITAL_ENTREPRISE PURGE;

-- Retrait de l'état d'entreprise EN_SUSPENS_FAILLITE (remplacé par EN_FAILLITE)
UPDATE ETAT_ENTREPRISE SET TYPE_ETAT='EN_FAILLITE' WHERE TYPE_ETAT='EN_SUSPENS_FAILLITE';

-- Nouvelle colonne sur la table TIERS pour stocker la date de début du premier exercice commercial d'une entreprise
ALTER TABLE TIERS ADD DATE_DEBUT_PREMIER_EXERCICE NUMBER(10,0);
UPDATE TIERS E SET DATE_DEBUT_PREMIER_EXERCICE = (SELECT MIN(DATE_OUVERTURE) FROM FOR_FISCAL FF WHERE FF.ANNULATION_DATE IS NULL AND FF.TIERS_ID = E.NUMERO AND FF.GENRE_IMPOT='BENEFICE_CAPITAL')
WHERE TIERS_TYPE='Entreprise';

-- Nouvelles colonnes sur les tables DECLARATION et TACHE pour stocker les dates de l'exercice commercial lié à une DI PM
ALTER TABLE DECLARATION ADD (DATE_DEBUT_EXERCICE NUMBER(10, 0), DATE_FIN_EXERCICE NUMBER(10, 0));
UPDATE DECLARATION SET DATE_DEBUT_EXERCICE=DATE_DEBUT, DATE_FIN_EXERCICE=DATE_FIN
WHERE DOCUMENT_TYPE='DIPM';
ALTER TABLE TACHE ADD (DECL_DATE_DEBUT_EXERCICE NUMBER(10, 0), DECL_DATE_FIN_EXERCICE NUMBER(10, 0));
UPDATE TACHE SET DECL_DATE_DEBUT_EXERCICE=DECL_DATE_DEBUT, DECL_DATE_FIN_EXERCICE=DECL_DATE_FIN
WHERE TACHE_TYPE='ENVOI_DI_PM';

-- Nouvelle colonne sur la table ETAT_ENTREPRISE pour ajouter un TYPE_GENERATION
ALTER TABLE ETAT_ENTREPRISE ADD TYPE_GENERATION NVARCHAR2(11);
UPDATE ETAT_ENTREPRISE SET TYPE_GENERATION='AUTOMATIQUE';
ALTER TABLE ETAT_ENTREPRISE MODIFY (TYPE_GENERATION NVARCHAR2(11) NOT NULL);

-- Nouvelles hiérarchie de classes autour des allègements fiscaux
ALTER TABLE ALLEGEMENT_FISCAL ADD (TYPE_ALLEGEMENT_ICC NVARCHAR2(25), TYPE_ALLEGEMENT_IFD NVARCHAR2(25));
ALTER TABLE ALLEGEMENT_FISCAL MODIFY (POURCENTAGE_ALLEGEMENT NUMBER(5,2) NULL, TYPE_COLLECTIVITE NVARCHAR2(15) NOT NULL);
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_ICC='ARTICLE_91_LI' WHERE TYPE_COLLECTIVITE IN ('CANTON', 'COMMUNE');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_IFD='DECISION_DFE' WHERE TYPE_COLLECTIVITE IN ('CONFEDERATION');