-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('5.10.0', '5.9.0_5.10.0_upgrade');

-- SIFISC-12815
ALTER TABLE EVENEMENT_IDENTIFICATION_CTB ADD COMMENTAIRE_TRAITEMENT nvarchar2(255);