
CREATE TABLE H_ADRESSE_POSTALE
(
  NO_ADR_POSTALE   NUMBER(19)                   NOT NULL,
  CHEZ             VARCHAR2(255 CHAR),
  DAA_ADR_POSTALE  DATE,
  DAD_VALIDITE     DATE,
  DAF_VALIDITE     DATE,
  DA_MUT           DATE,
  FK_EMPNO         NUMBER(10),
  FK_LOCNO         NUMBER(10),
  FK_PAYSNO_OFS    NUMBER(10),
  FK_RUENO         NUMBER(10),
  FK_SOUNO         NUMBER(10),
  HR_MUT           DATE,
  LIEU             VARCHAR2(255 CHAR),
  NO_MAJ           NUMBER(10),
  NO_POLICE        VARCHAR2(255 CHAR),
  RUE              VARCHAR2(255 CHAR),
  TY_ADRESSE       VARCHAR2(255 CHAR),
  VILLE_ETRANGER   VARCHAR2(255 CHAR),
  VS_MUT           VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_ADR_FISCALE
(
  FK_SOUNO            NUMBER(19)                NOT NULL,
  NO_SEQUENCE         NUMBER(19)                NOT NULL,
  COMMENTAIRE         VARCHAR2(255 CHAR),
  DAA_ADR_FISCALE     TIMESTAMP(6),
  DAD_ADR_FISCALE     TIMESTAMP(6),
  DAF_ADR_FISCALE     TIMESTAMP(6),
  DA_DEPART_ETRANGER  TIMESTAMP(6),
  DA_MUT              TIMESTAMP(6),
  DA_RETOUR_ETRANGER  TIMESTAMP(6),
  FK_COMNO            NUMBER(10),
  HR_MUT              TIMESTAMP(6),
  NO_MAJ              NUMBER(10),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_CATEGORIE_EMPLOYEUR
(
  NO_CATEGORIE  NUMBER(19)                      NOT NULL,
  CATEGORIE     VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_COMMUNE
(
  NO_TECHNIQUE        NUMBER(19)                NOT NULL,
  CO_LOC_BIENS_FISC   VARCHAR2(255 CHAR),
  DAD_VALIDITE        DATE,
  DAF_VALIDITE        DATE,
  DA_MUT              DATE,
  FK_CANTONSIGLE      VARCHAR2(255 CHAR),
  FK_COLLECTNO        NUMBER(10),
  FK_COMMUNENO        NUMBER(10),
  HR_MUT              DATE,
  NOM_ABREGE_OFS_MIN  VARCHAR2(255 CHAR),
  NOM_OFS_MAJ         VARCHAR2(255 CHAR),
  NOM_OFS_MIN         VARCHAR2(255 CHAR),
  NO_ACI              VARCHAR2(255 CHAR),
  NO_CANTONAL         VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_NEUCHATEL        NUMBER(10),
  NO_OFS              VARCHAR2(255 CHAR),
  NO_TVA              VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_CONTRIBUABLE
(
  NO_CONTRIBUABLE     NUMBER(19)                NOT NULL,
  BIC                 VARCHAR2(255 CHAR),
  BLOCAGE_REMB_AUTO   VARCHAR2(255 CHAR),
  CHEZ                VARCHAR2(255 CHAR),
  CO_IROLE            VARCHAR2(255 CHAR),
  DAD_RECOMMANDE      DATE,
  DAF_RECOMMANDE      DATE,
  DA_MUT              DATE,
  EMAIL               VARCHAR2(255 CHAR),
  FK_ADR_INDNO        NUMBER(10),
  FK_INDIVI_NO_IND    NUMBER(10),
  FK_INDNO            NUMBER(10),
  FK_INSTIT_FINNO     NUMBER(10),
  FK_LOC_POSNO        NUMBER(10),
  FK_PAYSNO_OFS       NUMBER(10),
  FK_RUENO            NUMBER(10),
  FORMULE_POLITESSE   VARCHAR2(255 CHAR),
  HR_MUT              DATE,
  IBAN                VARCHAR2(255 CHAR),
  IMPOT_DEPENSE_CH    VARCHAR2(255 CHAR),
  IMPOT_DEPENSE_VD    VARCHAR2(255 CHAR),
  INDIGENT            VARCHAR2(255 CHAR),
  LIEU                VARCHAR2(255 CHAR),
  MOTIF_ENVOI_RECETT  VARCHAR2(255 CHAR),
  NOM_COURRIER_1      VARCHAR2(255 CHAR),
  NOM_COURRIER_2      VARCHAR2(255 CHAR),
  NO_CCP              VARCHAR2(255 CHAR),
  NO_COMPTE_BANCAIRE  VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_POLICE           VARCHAR2(255 CHAR),
  NO_TEL_FIXE         VARCHAR2(255 CHAR),
  NO_TEL_PORTABLE     VARCHAR2(255 CHAR),
  ORIGINE_I107        VARCHAR2(255 CHAR),
  RECOMMANDE          VARCHAR2(255 CHAR),
  RUE                 VARCHAR2(255 CHAR),
  SOURCIER_MIXTE      VARCHAR2(255 CHAR),
  TITULAIRE_DU_COMPT  VARCHAR2(255 CHAR),
  VS_IMP_DEPENSE_CH   VARCHAR2(255 CHAR),
  VS_IMP_DEPENSE_VD   VARCHAR2(255 CHAR),
  VS_INDIGENT         VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR),
  VS_RECOMMANDE       VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_EMPLOYEUR
(
  NO_EMPLOYEUR        NUMBER(19)                NOT NULL,
  ACTIF               VARCHAR2(255 CHAR),
  CORRESPONDANT       VARCHAR2(255 CHAR),
  CO_MOD_PAIEMENT     VARCHAR2(255 CHAR),
  CO_PERIODICITE      VARCHAR2(255 CHAR),
  CO_RAPPEL           VARCHAR2(255 CHAR),
  DA_MUT              DATE,
  DESIGNATION_1       VARCHAR2(255 CHAR),
  DESIGNATION_2       VARCHAR2(255 CHAR),
  DESIGNATION_3       VARCHAR2(255 CHAR),
  DESIGNATION_4       VARCHAR2(255 CHAR),
  DESIGN_ABREGEE      VARCHAR2(255 CHAR),
  FK_CAT_NOEMPL       NUMBER(10),
  FK_COLLECTNO        NUMBER(10),
  FK_ENTPRNO          NUMBER(10),
  FK_INSTIT_FINNO     NUMBER(10),
  FK_MANDATAIRENO     NUMBER(10),
  FK_SECTACTNO        VARCHAR2(255 CHAR),
  HR_MUT              DATE,
  NBRE_PG_LIST_NOMIN  NUMBER(10),
  NO_COMPTE_BANQUE    VARCHAR2(255 CHAR),
  NO_COMPTE_POSTAL    VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_TELEPHONE        VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_ENTREPRISE
(
  NO_ENTREPRISE       NUMBER(19)                NOT NULL,
  COMMENT_LIVR_RECET  VARCHAR2(255 CHAR),
  COTEE_BOURSE        VARCHAR2(255 CHAR),
  CO_EXCLUS_DEGREV    VARCHAR2(255 CHAR),
  CPT_PIECE_COMPTABL  NUMBER(10),
  DAD_LIVR_RECETTE    TIMESTAMP(6),
  DAD_STE_PERSONNES   TIMESTAMP(6),
  DAF_FISCALE         TIMESTAMP(6),
  DAF_LIVR_RECETTE    TIMESTAMP(6),
  DAF_STE_PERSONNES   TIMESTAMP(6),
  DA_AUT_RADIATION    TIMESTAMP(6),
  DA_BOUCL_FUTUR      TIMESTAMP(6),
  DA_CONSTITUTION     TIMESTAMP(6),
  DA_DISSOLUTION      TIMESTAMP(6),
  DA_INSC_RC_VD       TIMESTAMP(6),
  DA_MUT              TIMESTAMP(6),
  DA_RAD_RC_VD        TIMESTAMP(6),
  DA_REQ_RADIATION    TIMESTAMP(6),
  DA_STATUTS          TIMESTAMP(6),
  DESIGN_ABREGEE      VARCHAR2(255 CHAR),
  ENSEIGNE            VARCHAR2(255 CHAR),
  ETABLISSEMENT_HC    VARCHAR2(255 CHAR),
  ETABLISSEMENT_HS    VARCHAR2(255 CHAR),
  FK_COMMUNENO        NUMBER(10),
  FK_INSTIT_FINNO     NUMBER(10),
  GRP_DOSSIERS        VARCHAR2(255 CHAR),
  HR_MUT              TIMESTAMP(6),
  LOI_REGLEMENT       VARCHAR2(255 CHAR),
  NATURE_DROIT        VARCHAR2(255 CHAR),
  NOM_CONTACT_1       VARCHAR2(255 CHAR),
  NOM_CONTACT_2       VARCHAR2(255 CHAR),
  NO_AFC              NUMBER(10),
  NO_CCP              VARCHAR2(255 CHAR),
  NO_COMPTE_BANCAIRE  VARCHAR2(255 CHAR),
  NO_FAX              VARCHAR2(255 CHAR),
  NO_FAX_CONTACT_1    VARCHAR2(255 CHAR),
  NO_FAX_CONTACT_2    VARCHAR2(255 CHAR),
  NO_IPMRO            VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_REE              VARCHAR2(255 CHAR),
  NO_TELEPHONE        VARCHAR2(255 CHAR),
  NO_TEL_CONTACT_1    VARCHAR2(255 CHAR),
  NO_TEL_CONTACT_2    VARCHAR2(255 CHAR),
  PRENOM_CONTACT_1    VARCHAR2(255 CHAR),
  PRENOM_CONTACT_2    VARCHAR2(255 CHAR),
  RAISON_SOC_LGN1     VARCHAR2(255 CHAR),
  RAISON_SOC_LGN2     VARCHAR2(255 CHAR),
  RAISON_SOC_LGN3     VARCHAR2(255 CHAR),
  RAIS_SOC_PROV_LGN1  VARCHAR2(255 CHAR),
  RAIS_SOC_PROV_LGN2  VARCHAR2(255 CHAR),
  RAIS_SOC_PROV_LGN3  VARCHAR2(255 CHAR),
  RECOMMANDE          VARCHAR2(255 CHAR),
  REGLEMENT_ENT       VARCHAR2(255 CHAR),
  TY_FONDATION        VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_HISTO_ROLE
(
  NO_TECHNIQUE       NUMBER(19)                 NOT NULL,
  DAA_MISE_ROLE      DATE,
  DAD_MISE_ROLE      DATE,
  DAF_MISE_ROLE      DATE,
  DA_MUT             DATE,
  FK_SOUNO           NUMBER(10),
  HR_MUT             DATE,
  NO_MAJ             NUMBER(10),
  NO_ROLE_ORDINAIRE  NUMBER(19,2),
  VS_MUT             VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_INDIVIDU
(
  NO_INDIVIDU         NUMBER(19)                NOT NULL,
  ADR_E_MAIL          VARCHAR2(255 CHAR),
  CO_DEMENAGEMENT     VARCHAR2(255 CHAR),
  CO_SEXE             VARCHAR2(255 CHAR),
  DATE_DECES          DATE,
  DATE_NAISSANCE      DATE,
  DA_MUT              DATE,
  DA_VALIDITE         DATE,
  FK_COMMUNENO_DCD    NUMBER(10),
  FK_COMMUNENO_ORG    NUMBER(10),
  FK_PAYSNO_OFS_DCD   NUMBER(10),
  FK_PAYSNO_OFS_ORG   NUMBER(10),
  GRP_DOSSIERS        VARCHAR2(255 CHAR),
  HR_MUT              DATE,
  IDENTIFIANT_CH      VARCHAR2(255 CHAR),
  NOM                 VARCHAR2(255 CHAR),
  NOM_MAJ             VARCHAR2(255 CHAR),
  NOM_SK1             VARCHAR2(255 CHAR),
  NOM_SK2             VARCHAR2(255 CHAR),
  NOM_SK3             VARCHAR2(255 CHAR),
  NO_CANTONAL         VARCHAR2(255 CHAR),
  NO_FAX              VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_RDCC             VARCHAR2(255 CHAR),
  NO_REF_CANTONAL     VARCHAR2(255 CHAR),
  NO_REGISTRE_ETRANG  VARCHAR2(255 CHAR),
  NO_TELEPHONE        VARCHAR2(255 CHAR),
  NO_TEL_AUTRE        VARCHAR2(255 CHAR),
  NO_TEL_PROF         VARCHAR2(255 CHAR),
  PRENOM              VARCHAR2(255 CHAR),
  PRENOM_MAJ          VARCHAR2(255 CHAR),
  PRENOM_SK1          VARCHAR2(255 CHAR),
  PRENOM_SK2          VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_LOCALITE_POSTALE
(
  NO_ORDRE_P          NUMBER(19)                NOT NULL,
  CHIFFRE_COMPLEMENT  NUMBER(10),
  DAD_VALIDITE        DATE,
  DAF_VALIDITE        DATE,
  DA_MUT              DATE,
  DESIGN_ABREGEE_MAJ  VARCHAR2(255 CHAR),
  DESIGN_ABREGEE_MIN  VARCHAR2(255 CHAR),
  FK_COMMUNENO        NUMBER(10),
  HR_MUT              DATE,
  NOM_COMPLET_MAJ     VARCHAR2(255 CHAR),
  NOM_COMPLET_MIN     VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_POSTAL_ACHEMIN   NUMBER(10),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_PAYS
(
  NO_OFS       NUMBER(19)                       NOT NULL,
  CO_ACI       VARCHAR2(255 CHAR),
  DA_MUT       DATE,
  HR_MUT       DATE,
  NOM_OFS_MAJ  VARCHAR2(255 CHAR),
  NOM_OFS_MIN  VARCHAR2(255 CHAR),
  NO_MAJ       NUMBER(10),
  VS_MUT       VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_PERMIS_TRAVAIL
(
  FK_SOUNO     NUMBER(19)                       NOT NULL,
  NO_SEQUENCE  NUMBER(19)                       NOT NULL,
  DAA_PERMIS   DATE,
  DAD_PERMIS   DATE,
  DAF_PERMIS   DATE,
  DA_MUT       DATE,
  HR_MUT       DATE,
  NO_MAJ       NUMBER(10),
  TY_PERMIS    VARCHAR2(255 CHAR),
  VS_MUT       VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_RAPPORT_TRAVAIL
(
  ID                NUMBER(19)                  NOT NULL,
  AUT_BAREME_C      VARCHAR2(255 CHAR),
  DAD_RAPPORT_TRAV  DATE,
  DAF_RAPPORT_TRAV  DATE,
  DA_MUT            DATE,
  FK_EMPNO          NUMBER(10),
  FK_SOUNO          NUMBER(10),
  HR_MUT            DATE,
  MOTIF             VARCHAR2(255 CHAR),
  NB_JOURS_TRAV     NUMBER(10),
  NO_MAJ            NUMBER(10),
  TY_ACTIVITE       VARCHAR2(255 CHAR),
  VS_MUT            VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_REMBOURSEMENT_IS
(
  NO_SEQUENCE         NUMBER(19)                NOT NULL,
  COMMENTAIRE_OID     VARCHAR2(255 CHAR),
  DA_ANNULATION       DATE,
  DA_CTBLN            DATE,
  DA_DECTBLN          DATE,
  DA_EXECUTION        DATE,
  DA_MUT              DATE,
  DA_REJET_PROCOFIEV  DATE,
  DA_RESERVATION      DATE,
  DA_TRANS_PROCOFIEV  DATE,
  FK_COLADMNO         NUMBER(10),
  FK_FSONOSEQ         NUMBER(10),
  FK_RISNO            NUMBER(10),
  FK_SOUNO            NUMBER(10),
  HR_MUT              DATE,
  INSTIT_FINANCIERE   VARCHAR2(255 CHAR),
  LIBELLE             VARCHAR2(255 CHAR),
  MT_REMBOURSE        NUMBER(19,2),
  NO_CCP              VARCHAR2(255 CHAR),
  NO_CLEARING         VARCHAR2(255 CHAR),
  NO_COMPTE_BQUE      VARCHAR2(255 CHAR),
  NO_MAJ              NUMBER(10),
  NO_PIECE_CHEQUE     VARCHAR2(255 CHAR),
  REF_PROCOFIEV       VARCHAR2(255 CHAR),
  TY_REMBOURSEMENT    VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_RUE
(
  NO_RUE           NUMBER(19)                   NOT NULL,
  DAD_VALIDITE     DATE,
  DAF_VALIDITE     DATE,
  DA_MUT           DATE,
  DESIGN_COURRIER  VARCHAR2(255 CHAR),
  DESIGN_MAJ       VARCHAR2(255 CHAR),
  DESIGN_MIN       VARCHAR2(255 CHAR),
  FK_GENRUECO      VARCHAR2(255 CHAR),
  FK_LOCPOSNO      NUMBER(10),
  HR_MUT           DATE,
  NO_MAJ           NUMBER(10),
  RADICAL          VARCHAR2(255 CHAR),
  VS_MUT           VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_SOURCIER
(
  NO_SOURCIER         NUMBER(19)                NOT NULL,
  AUTRES_PRENOMS      VARCHAR2(255 CHAR),
  CATEGORIE_SOURCIER  VARCHAR2(255 CHAR),
  COMPLEMENT_IDENTIF  VARCHAR2(255 CHAR),
  CONFESSION          VARCHAR2(255 CHAR),
  CO_ASSUJETTISSEMEN  VARCHAR2(255 CHAR),
  CO_TO               VARCHAR2(255 CHAR),
  DAF_PERMIS_TRAVAIL  DATE,
  DATE_MISE_ROLE_ORD  DATE,
  DATE_NAISSANCE      DATE,
  DA_ACC_SIMULT_C27   DATE,
  DA_ACC_SIMULT_DIS   DATE,
  DA_MUT              DATE,
  EMPLOYEUR           VARCHAR2(255 CHAR),
  FK_MANDATAIRENO     NUMBER(10),
  FK_PAYSNO           NUMBER(10),
  FK_SOURCIERNO       NUMBER(10),
  HR_MUT              DATE,
  LANGUE              VARCHAR2(255 CHAR),
  NOM                 VARCHAR2(255 CHAR),
  NOM_NAISSANCE       VARCHAR2(255 CHAR),
  NO_AVS              NUMBER(19,2),
  NO_IND_REG_FISCAL   NUMBER(10),
  NO_MAJ              NUMBER(10),
  NO_REF_CANTONAL     VARCHAR2(255 CHAR),
  NO_REGISTRE_ETRANG  VARCHAR2(255 CHAR),
  NO_ROLE_ORDINAIRE   NUMBER(19,2),
  PRENOM              VARCHAR2(255 CHAR),
  PROFESSION          VARCHAR2(255 CHAR),
  REMARQUE            VARCHAR2(255 CHAR),
  SEXE                VARCHAR2(255 CHAR),
  TYPE_PERMIS         VARCHAR2(255 CHAR),
  VS_MUT              VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE H_TY_IMPOSITION
(
  FK_SOUNO        NUMBER(19)                    NOT NULL,
  NO_SEQUENCE     NUMBER(19)                    NOT NULL,
  DAA_TY_IMPOSIT  TIMESTAMP(6),
  DAD_TY_IMPOSIT  TIMESTAMP(6),
  DAF_TY_IMPOSIT  TIMESTAMP(6),
  DA_MUT          TIMESTAMP(6),
  HR_MUT          TIMESTAMP(6),
  MOTIF_DEBUT     VARCHAR2(255 CHAR),
  MOTIF_FIN       VARCHAR2(255 CHAR),
  NO_MAJ          NUMBER(10),
  TY_IMPOSIT      VARCHAR2(255 CHAR),
  VS_MUT          VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IDX_FK_SOUNO ON H_ADRESSE_POSTALE
(FK_SOUNO)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_FK_EMPNO ON H_ADRESSE_POSTALE
(FK_EMPNO)
LOGGING
NOPARALLEL;


ALTER TABLE H_ADRESSE_POSTALE ADD (
  PRIMARY KEY
 (NO_ADR_POSTALE));


ALTER TABLE H_ADR_FISCALE ADD (
  PRIMARY KEY
 (FK_SOUNO, NO_SEQUENCE));


ALTER TABLE H_CATEGORIE_EMPLOYEUR ADD (
  PRIMARY KEY
 (NO_CATEGORIE));


ALTER TABLE H_COMMUNE ADD (
  PRIMARY KEY
 (NO_TECHNIQUE));


ALTER TABLE H_CONTRIBUABLE ADD (
  PRIMARY KEY
 (NO_CONTRIBUABLE));


ALTER TABLE H_EMPLOYEUR ADD (
  PRIMARY KEY
 (NO_EMPLOYEUR));


ALTER TABLE H_ENTREPRISE ADD (
  PRIMARY KEY
 (NO_ENTREPRISE));


ALTER TABLE H_HISTO_ROLE ADD (
  PRIMARY KEY
 (NO_TECHNIQUE));


ALTER TABLE H_INDIVIDU ADD (
  PRIMARY KEY
 (NO_INDIVIDU));


ALTER TABLE H_LOCALITE_POSTALE ADD (
  PRIMARY KEY
 (NO_ORDRE_P));


ALTER TABLE H_PAYS ADD (
  PRIMARY KEY
 (NO_OFS));


ALTER TABLE H_PERMIS_TRAVAIL ADD (
  PRIMARY KEY
 (FK_SOUNO, NO_SEQUENCE));


ALTER TABLE H_RAPPORT_TRAVAIL ADD (
  PRIMARY KEY
 (ID));


ALTER TABLE H_REMBOURSEMENT_IS ADD (
  PRIMARY KEY
 (NO_SEQUENCE));


ALTER TABLE H_RUE ADD (
  PRIMARY KEY
 (NO_RUE));


ALTER TABLE H_SOURCIER ADD (
  PRIMARY KEY
 (NO_SOURCIER));


ALTER TABLE H_TY_IMPOSITION ADD (
  PRIMARY KEY
 (FK_SOUNO, NO_SEQUENCE));



