-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.1.1', '6.1.0_6.1.1_upgrade');

--
-- Nouveau événements fiscaux
--

UPDATE EVENEMENT_FISCAL SET EVT_TYPE='DECLARATION_SOMMABLE' WHERE EVT_TYPE='DECLARATION';

--
-- [SIFISC-19345] Fusion des motifs de fermeture de for CESSATION_ACTIVITE et FIN_EXPLOITATION en FIN_EXPLOITATION
--

UPDATE FOR_FISCAL SET MOTIF_OUVERTURE='FIN_EXPLOITATION' WHERE MOTIF_OUVERTURE='CESSATION_ACTIVITE';
UPDATE FOR_FISCAL SET MOTIF_FERMETURE='FIN_EXPLOITATION' WHERE MOTIF_FERMETURE='CESSATION_ACTIVITE';

--
-- Attributs "withCopy" et "codeGenreImpot" sur les liens de type mandat
--

ALTER TABLE RAPPORT_ENTRE_TIERS ADD (WITH_COPY_MANDAT NUMBER(1,0), GENRE_IMPOT_MANDAT NVARCHAR2(10));
UPDATE RAPPORT_ENTRE_TIERS SET WITH_COPY_MANDAT=1 WHERE RAPPORT_ENTRE_TIERS_TYPE='Mandat' AND TYPE_MANDAT IN ('GENERAL');
ALTER TABLE ADRESSE_MANDATAIRE ADD (WITH_COPY NUMBER(1,0), GENRE_IMPOT NVARCHAR2(10));
UPDATE ADRESSE_MANDATAIRE SET WITH_COPY=1;
ALTER TABLE ADRESSE_MANDATAIRE MODIFY (WITH_COPY NUMBER(1,0) NOT NULL);
