-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.1.1', '6.1.0_6.1.1_upgrade');

--
-- Nouveau événements fiscaux
--

UPDATE EVENEMENT_FISCAL SET EVT_TYPE='DECLARATION_SOMMABLE' WHERE EVT_TYPE='DECLARATION';