-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.1.1', '6.1.0_6.1.1_upgrade');

--
-- Nouveau événements fiscaux
--

UPDATE EVENEMENT_FISCAL SET EVT_TYPE='DECLARATION_SOMMABLE' WHERE EVT_TYPE='DECLARATION';

--
-- [SIFISC-19345] Fusion des motifs de fermeture de for CESSATION_ACTIVITE et FIN_EXPLOITATION en FIN_EXPLOITATION
--

UPDATE FOR_FISCAL SET MOTIF_OUVERTURE='FIN_EXPLOITATION' WHERE MOTIF_OUVERTURE='CESSATION_ACTIVITE';
UPDATE FOR_FISCAL SET MOTIF_FERMETURE='FIN_EXPLOITATION' WHERE MOTIF_FERMETURE='CESSATION_ACTIVITE';