-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.1.1', '6.0.9_6.1.1_upgrade');

--
-- Ajout de paramétres périodiques autour des questionnaires SNC
--

ALTER TABLE PARAMETRE_PERIODE_FISCALE ADD (SNC_RAPPEL_IMPRIME NUMBER(10,0), SNC_RAPPEL_EFFECTIF NUMBER(10,0));
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, SNC_RAPPEL_IMPRIME, SNC_RAPPEL_EFFECTIF)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'SNC', PF.ID, (PF.ANNEE + 1) * 10000 + 315, (PF.ANNEE + 1) * 10000 + 831 FROM PERIODE_FISCALE PF;

--
-- Nouveau événements fiscaux
--

UPDATE EVENEMENT_FISCAL SET EVT_TYPE='DECLARATION_SOMMABLE' WHERE EVT_TYPE='DECLARATION';

--
-- [SIFISC-19345] Fusion des motifs de fermeture de for CESSATION_ACTIVITE et FIN_EXPLOITATION en FIN_EXPLOITATION
--

UPDATE FOR_FISCAL SET MOTIF_OUVERTURE='FIN_EXPLOITATION' WHERE MOTIF_OUVERTURE='CESSATION_ACTIVITE';
UPDATE FOR_FISCAL SET MOTIF_FERMETURE='FIN_EXPLOITATION' WHERE MOTIF_FERMETURE='CESSATION_ACTIVITE';