-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.1.0', '7.0.3_7.1.0_upgrade');

-- SIFISC-22396 - import des servitudes
ALTER TABLE EVENEMENT_RF_IMPORT ADD TYPE NVARCHAR2(13) NULL;
UPDATE EVENEMENT_RF_IMPORT set TYPE = 'PRINCIPAL' where TYPE is null;
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY TYPE NOT NULL;
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY ETAT NOT NULL;


-- Nouveaux emplacements pour les clés de visualisation des documents dans RepElec
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD (CLE_DOCUMENT NVARCHAR2(256) NULL, CLE_DOCUMENT_RAPPEL NVARCHAR2(256) NULL);
ALTER TABLE ETAT_DECLARATION ADD CLE_DOCUMENT NVARCHAR2(256) NULL;
ALTER TABLE DELAI_DECLARATION ADD CLE_DOCUMENT NVARCHAR2(256) NULL;
CREATE TABLE DOCUMENT_EFACTURE (
	ID NUMBER(19,0) NOT NULL,
	ANNULATION_DATE TIMESTAMP,
	ANNULATION_USER NVARCHAR2(65),
	LOG_CDATE TIMESTAMP,
	LOG_CUSER NVARCHAR2(65),
	LOG_MDATE TIMESTAMP,
	LOG_MUSER NVARCHAR2(65),
	TIERS_ID NUMBER(19,0) NOT NULL,
	CLE_ARCHIVAGE NVARCHAR2(40) NOT NULL,
	CLE_DOCUMENT NVARCHAR2(256) NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_DOC_EFACTURE_TIERS_ID FOREIGN KEY (TIERS_ID) REFERENCES TIERS (NUMERO)
);
CREATE UNIQUE INDEX IDX_DOC_EFACTURE_CLE ON DOCUMENT_EFACTURE(TIERS_ID ASC, CLE_ARCHIVAGE ASC);