-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.1.0', '7.0.3_7.1.0_upgrade');

-- SIFISC-22396 - import des servitudes
ALTER TABLE EVENEMENT_RF_IMPORT ADD TYPE NVARCHAR2(13) NULL;
UPDATE EVENEMENT_RF_IMPORT set TYPE = 'PRINCIPAL' where TYPE is null;
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY TYPE NOT NULL;
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY ETAT NOT NULL;