-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.0.2', '7.0.1_7.0.2_upgrade');

-- SIFISC-23194 annulation des tâches assignées à la collectivité 25 (= nouvelle entité) pour des PF < 2015
UPDATE TACHE SET ANNULATION_DATE=CURRENT_DATE, ANNULATION_USER='SQL-SIFISC-23194', LOG_MDATE=CURRENT_DATE, LOG_MUSER='SQL-SIFISC-23194'
WHERE ANNULATION_DATE IS NULL
			AND ETAT='EN_INSTANCE'
			AND TACHE_TYPE = 'ENVOI_DI_PP'
			AND CA_ID = (SELECT NUMERO FROM TIERS WHERE NUMERO_CA=25)
			AND DECL_DATE_FIN < 20150000;