-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('3.3.5', '3.3.3_3.3.5_upgrade');

-- Correction de la taille de la colonne MESSAGE dans la table EVENEMENT_CIVIL_ERREUR
ALTER TABLE EVENEMENT_CIVIL_ERREUR MODIFY (MESSAGE VARCHAR2(1024 CHAR));