-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('18R4.B', '18R3.A_18R4.B_upgrade');

-- [FISCPROJ-504] traitement des demandes de délais groupées
create table DEMANDE_MANDATAIRE
(
    ID NUMBER(19) not null,
    ANNULATION_DATE TIMESTAMP(6),
    ANNULATION_USER NVARCHAR2(65),
    LOG_CDATE TIMESTAMP(6),
    LOG_CUSER NVARCHAR2(65),
    LOG_MDATE TIMESTAMP(6),
    LOG_MUSER NVARCHAR2(65),
    BUSINESS_ID NVARCHAR2(255) not null,
    NUMERO_CTB_MANDATAIRE NUMBER(19),
    NUMERO_IDE_MANDATAIRE NVARCHAR2(255) not null,
    RAISON_SOCIALE_MANDATAIRE NVARCHAR2(255) not null,
    REFERENCE_ID NVARCHAR2(255),
    primary key (ID)
);

alter table DELAI_DOCUMENT_FISCAL add DEMANDE_MANDATAIRE_ID NUMBER(19);
alter table DELAI_DOCUMENT_FISCAL add constraint FK_DELAI_DEM_MAND_ID foreign key (DEMANDE_MANDATAIRE_ID) references DEMANDE_MANDATAIRE;
create index IDX_DELAI_DEM_MAND_ID on DELAI_DOCUMENT_FISCAL (DEMANDE_MANDATAIRE_ID);

