-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.0.1', '7.0.0_7.0.1_upgrade');

-- Ajout de l'état EN_TRAITEMENT
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY ETAT NVARCHAR2(13);

-- [SIFISC-21987] Ajout des demandes de dégrèvement
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DATE_DEBUT NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DELAI_RAPPEL NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_MOTIF_ENVOI NVARCHAR2(33);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_PERIODE_FISCALE NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_IMMEUBLE_ID NUMBER(19);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DATE_FIN NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD CONSTRAINT FK_DD_RF_IMMEUBLE_ID FOREIGN KEY (DD_IMMEUBLE_ID) REFERENCES RF_IMMEUBLE (ID);
CREATE INDEX IDX_DD_RF_IMMEUBLE_ID ON AUTRE_DOCUMENT_FISCAL (DD_IMMEUBLE_ID);

-- [SIFISC-21688] déblocage des flags de remboursement automatique des entreprises
UPDATE TIERS T
SET T.LOG_MUSER='SQL-SIFISC-21688', T.LOG_MDATE=CURRENT_DATE, T.BLOC_REMB_AUTO=0
WHERE T.BLOC_REMB_AUTO=1
			AND T.TIERS_TYPE='Entreprise'
			AND T.ANNULATION_DATE IS NULL
			AND EXISTS (SELECT 1 FROM FOR_FISCAL FF
									WHERE FF.ANNULATION_DATE IS NULL
											AND FF.DATE_FERMETURE IS NULL
											AND FF.TYPE_AUT_FISC='COMMUNE_OU_FRACTION_VD'
											AND FF.TIERS_ID=T.NUMERO)
			AND NOT EXISTS(SELECT 1
										 FROM ETAT_ENTREPRISE EE
										 WHERE EE.ANNULATION_DATE IS NULL
													 AND EE.ENTREPRISE_ID = T.NUMERO
													 AND EE.TYPE_ETAT = 'EN_FAILLITE'
													 AND EE.DATE_OBTENTION = (SELECT MAX(EE2.DATE_OBTENTION)
																										FROM ETAT_ENTREPRISE EE2
																										WHERE EE2.ENTREPRISE_ID = EE.ENTREPRISE_ID
																													AND EE2.ANNULATION_DATE IS NULL));

-- SIFISC-20373 : performances du WS du registre foncier
CREATE INDEX IDX_DROIT_RF_COMM_ID ON RF_DROIT (COMMUNAUTE_ID);