-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.0.1', '7.0.0_7.0.1_upgrade');

-- Ajout de l'état EN_TRAITEMENT
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY ETAT NVARCHAR2(13);

-- [SIFISC-21987] Ajout des demandes de dégrèvement
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DATE_DEBUT NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DELAI_RAPPEL NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_MOTIF_ENVOI NVARCHAR2(33);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_PERIODE_FISCALE NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_IMMEUBLE_ID NUMBER(19);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DATE_FIN NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD CONSTRAINT FK_DD_RF_IMMEUBLE_ID FOREIGN KEY (DD_IMMEUBLE_ID) REFERENCES RF_IMMEUBLE (ID);
CREATE INDEX IDX_DD_RF_IMMEUBLE_ID ON AUTRE_DOCUMENT_FISCAL (DD_IMMEUBLE_ID);