-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.0.1', '7.0.0_7.0.1_upgrade');

-- Ajout de l'état EN_TRAITEMENT
ALTER TABLE EVENEMENT_RF_IMPORT MODIFY ETAT NVARCHAR2(13);

-- [SIFISC-21987] Ajout des demandes de dégrèvement
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DATE_DEBUT NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DELAI_RAPPEL NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_MOTIF_ENVOI NVARCHAR2(33);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_PERIODE_FISCALE NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_IMMEUBLE_ID NUMBER(19);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_DATE_FIN NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD CONSTRAINT FK_DD_RF_IMMEUBLE_ID FOREIGN KEY (DD_IMMEUBLE_ID) REFERENCES RF_IMMEUBLE (ID);
CREATE INDEX IDX_DD_RF_IMMEUBLE_ID ON AUTRE_DOCUMENT_FISCAL (DD_IMMEUBLE_ID);

-- [SIFISC-21688] déblocage des flags de remboursement automatique des entreprises
UPDATE TIERS T
SET T.LOG_MUSER='SQL-SIFISC-21688', T.LOG_MDATE=CURRENT_DATE, T.BLOC_REMB_AUTO=0
WHERE T.BLOC_REMB_AUTO=1
			AND T.TIERS_TYPE='Entreprise'
			AND T.ANNULATION_DATE IS NULL
			AND EXISTS (SELECT 1 FROM FOR_FISCAL FF
									WHERE FF.ANNULATION_DATE IS NULL
											AND FF.DATE_FERMETURE IS NULL
											AND FF.TYPE_AUT_FISC='COMMUNE_OU_FRACTION_VD'
											AND FF.TIERS_ID=T.NUMERO)
			AND NOT EXISTS(SELECT 1
										 FROM ETAT_ENTREPRISE EE
										 WHERE EE.ANNULATION_DATE IS NULL
													 AND EE.ENTREPRISE_ID = T.NUMERO
													 AND EE.TYPE_ETAT = 'EN_FAILLITE'
													 AND EE.DATE_OBTENTION = (SELECT MAX(EE2.DATE_OBTENTION)
																										FROM ETAT_ENTREPRISE EE2
																										WHERE EE2.ENTREPRISE_ID = EE.ENTREPRISE_ID
																													AND EE2.ANNULATION_DATE IS NULL));

-- SIFISC-20373 : performances du WS du registre foncier
CREATE INDEX IDX_DROIT_RF_COMM_ID ON RF_DROIT (COMMUNAUTE_ID);

-- Demandes de dégrèvement
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_NUMERO_SEQUENCE NUMBER(10);
ALTER TABLE AUTRE_DOCUMENT_FISCAL ADD DD_CODE_CONTROLE NVARCHAR2(6);
ALTER TABLE AUTRE_DOCUMENT_FISCAL DROP COLUMN DD_DATE_DEBUT;
ALTER TABLE AUTRE_DOCUMENT_FISCAL DROP COLUMN DD_DELAI_RAPPEL;
ALTER TABLE AUTRE_DOCUMENT_FISCAL DROP COLUMN DD_MOTIF_ENVOI;
ALTER TABLE AUTRE_DOCUMENT_FISCAL DROP COLUMN DD_DATE_FIN;

-- Information de valeurs d'allégements pour l'IFONC et l'ICI (= dégrèvements)
CREATE TABLE ALLEGEMENT_FONCIER (
	ID NUMBER(19,0) NOT NULL,
	TYPE_ALLEGEMENT NVARCHAR2(20) NOT NULL,
	ANNULATION_DATE TIMESTAMP,
	ANNULATION_USER NVARCHAR2(65),
	LOG_CDATE TIMESTAMP,
	LOG_CUSER NVARCHAR2(65),
	LOG_MDATE TIMESTAMP,
	LOG_MUSER NVARCHAR2(65),
	DATE_DEBUT NUMBER(10,0) NOT NULL,
	DATE_FIN NUMBER(10,0),
	CTB_ID NUMBER(19,0) NOT NULL,
	IMMEUBLE_ID NUMBER(19,0) NOT NULL,
	DEG_LOC_REVENU NUMBER(10,0),
	DEG_LOC_VOLUME NUMBER(10,0),
	DEG_LOC_SURFACE NUMBER(10,0),
	DEG_LOC_POURCENT NUMBER(5,2),
	DEG_LOC_POURCENT_ARRETE NUMBER(5,2),
	DEG_PRUS_REVENU NUMBER(10,0),
	DEG_PRUS_VOLUME NUMBER(10,0),
	DEG_PRUS_SURFACE NUMBER(10,0),
	DEG_PRUS_POURCENT NUMBER(5,2),
	DEG_PRUS_POURCENT_ARRETE NUMBER(5,2),
	DEG_LL_OCTROI NUMBER(10,0),
	DEG_LL_ECHEANCE NUMBER(10,0),
	IFONC_POURCENT_ALLGT NUMBER(5,2),
	PRIMARY KEY (ID)
);
ALTER TABLE ALLEGEMENT_FONCIER ADD CONSTRAINT FK_AFONC_CTB_ID FOREIGN KEY (CTB_ID) REFERENCES TIERS (NUMERO);
ALTER TABLE ALLEGEMENT_FONCIER ADD CONSTRAINT FK_AFONC_RF_IMMEUBLE_ID FOREIGN KEY (IMMEUBLE_ID) REFERENCES RF_IMMEUBLE (ID);
CREATE INDEX IDX_AFONC_CTB_ID ON ALLEGEMENT_FONCIER (CTB_ID);
CREATE INDEX IDX_AFONC_RF_IMMEUBLE_ID ON ALLEGEMENT_FONCIER (IMMEUBLE_ID);

--
-- Mise à null de toutes les dates de début correspondant au premier import
--
ALTER TABLE RF_DESCRIPTION_BATIMENT MODIFY DATE_DEBUT NUMBER(10) NULL;
ALTER TABLE RF_DROIT MODIFY DATE_DEBUT NUMBER(10) NULL;
ALTER TABLE RF_ESTIMATION MODIFY DATE_DEBUT NUMBER(10) NULL;
ALTER TABLE RF_IMPLANTATION MODIFY DATE_DEBUT NUMBER(10) NULL;
ALTER TABLE RF_SITUATION MODIFY DATE_DEBUT NUMBER(10) NULL;
ALTER TABLE RF_SURFACE_AU_SOL MODIFY DATE_DEBUT NUMBER(10) NULL;
ALTER TABLE RF_SURFACE_TOTALE MODIFY DATE_DEBUT NUMBER(10) NULL;

UPDATE RF_DESCRIPTION_BATIMENT SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;
UPDATE RF_DROIT SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;
UPDATE RF_ESTIMATION SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;
UPDATE RF_IMPLANTATION SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;
UPDATE RF_SITUATION SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;
UPDATE RF_SURFACE_AU_SOL SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;
UPDATE RF_SURFACE_TOTALE SET DATE_DEBUT = NULL WHERE DATE_DEBUT=20160913;

--
-- Le régime de propriété n'existe que sur les droits de propriété... la colonne doit donc être nullable
--
ALTER TABLE RF_DROIT MODIFY REGIME_PROPRIETE NVARCHAR2(12) NULL;

-- Renommage de la colonne pour coller au plus près de la signification métier
ALTER TABLE RF_ESTIMATION RENAME COLUMN DATE_ESTIMATION TO DATE_INSCRIPTION;

--
--SIFISC-22442 événement fiscal Impression fourre neutre ajout de la période
ALTER TABLE EVENEMENT_FISCAL ADD (PERIODE_FISCALE NUMBER(10,0));