-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('5.1.2', '5.1.1_5.1.2_upgrade');

-- [SIFISC-5349]
ALTER TABLE TIERS MODIFY (NH_CAT_ETRANGER NVARCHAR2(50));
update tiers set NH_CAT_ETRANGER = '_04_CONJOINT_DIPLOMATE_OU_FONCT_INT_CI' where NH_CAT_ETRANGER = '_04_CONJOINT_DIPLOMATE_CI';
update tiers set NH_CAT_ETRANGER = '_11_DIPLOMATE_OU_FONCTIONNAIRE_INTERNATIONAL' where NH_CAT_ETRANGER in ('_11_DIPLOMATE', '_12_FONCTIONNAIRE_INTERNATIONAL');
