-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('5.1.2', '5.1.1_5.1.2_upgrade');

-- [SIFISC-5349]
ALTER TABLE TIERS MODIFY (NH_CAT_ETRANGER NVARCHAR2(50));
update tiers set NH_CAT_ETRANGER = '_11_DIPLOMATE_OU_FONCT_INTER_AVEC_IMMUNITE' where NH_CAT_ETRANGER = '_11_DIPLOMATE';
update tiers set NH_CAT_ETRANGER = '_12_FONCT_INTER_SANS_IMMUNITE' where NH_CAT_ETRANGER = '_12_FONCTIONNAIRE_INTERNATIONAL';