-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('4.9.0', '4.7.0_4.9.0_upgrade');

--
-- Suppression de la colonne NUMERO_PM qui dupliquait les données de la colonne NUMERO. 
--
ALTER TABLE TIERS DROP COLUMN NUMERO_PM;

--
-- [UNIREG-2920] Réindexation des collectivités administratives
--
update TIERS set INDEX_DIRTY = 1 where TIERS_TYPE = 'CollectiviteAdministrative';

--
-- [UNIREG-3125] Identification CTB :
--
ALTER TABLE EVENEMENT_IDENTIFICATION_CTB ADD (TRAITEMENT_USER nvarchar2(65));

ALTER TABLE EVENEMENT_IDENTIFICATION_CTB ADD (DATE_TRAITEMENT timestamp);

UPDATE EVENEMENT_IDENTIFICATION_CTB SET DATE_TRAITEMENT = LOG_MDATE, TRAITEMENT_USER = LOG_MUSER
WHERE ETAT IN ('TRAITE_MANUELLEMENT','TRAITE_AUTOMATIQUEMENT','TRAITE_MAN_EXPERT','NON_IDENTIFIE');


--
-- [UNIREG-3134] date envoi de courrier pour la sommation des DI :
--

ALTER TABLE ETAT_DECLARATION ADD (DATE_ENVOI_COURRIER number(10,0));

UPDATE ETAT_DECLARATION SET DATE_ENVOI_COURRIER = DATE_OBTENTION WHERE TYPE = 'SOMMEE';

UPDATE ETAT_DECLARATION SET DATE_OBTENTION = TO_CHAR(LOG_CDATE, 'YYYYMMDD')  WHERE TYPE = 'SOMMEE' AND DATE_OBTENTION >= 20090713;
