-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('5.10.1', '5.10.0_5.10.1_upgrade');

-- SIFISC-13461
ALTER TABLE TIERS ADD DPI_ACI_HC NUMBER(1, 0);
UPDATE TIERS SET DPI_ACI_HC=0 WHERE TIERS_TYPE='DebiteurPrestationImposable';
