-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.2.1', '7.2.0_7.2.1_upgrade');

--
-- SIFISC-25180 : alongement de la colonne NOM_DESTINATAIRE de la table ADRESSE_MANDATAIRE
--
ALTER TABLE ADRESSE_MANDATAIRE MODIFY NOM_DESTINATAIRE NVARCHAR2(182);