package ch.vd.uniregctb.dbutils;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.Map;

import ch.vd.uniregctb.common.ExceptionUtils;

/**
 * Connection de débugging qui stocke la callstack de l'appelant à l'ouverture.
 *
 * @author Manuel Siggen <manuel.siggen@vd.ch>
 */
public class DebugConnection implements Connection {

	private final DebugDataSource dataSource;
	private final Connection target;
	private String callerTrace;

	public DebugConnection(DebugDataSource dataSource, Connection target) {
		this.dataSource = dataSource;
		this.target = target;
		dataSource.register(this);
		initCallerTrace();
	}

	private void initCallerTrace() {
		callerTrace = ExceptionUtils.extractCallStack(new Exception());
	}

	public String getCallerTrace() {
		return callerTrace;
	}

	public void clearWarnings() throws SQLException {
		target.clearWarnings();
	}

	public void close() throws SQLException {
		target.close();
		dataSource.unregister(this);
		callerTrace = null;
	}

	public void commit() throws SQLException {
		target.commit();
	}

	public Statement createStatement() throws SQLException {
		return target.createStatement();
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return target.createStatement(resultSetType, resultSetConcurrency);
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return target.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public boolean getAutoCommit() throws SQLException {
		return target.getAutoCommit();
	}

	public String getCatalog() throws SQLException {
		return target.getCatalog();
	}

	public int getHoldability() throws SQLException {
		return target.getHoldability();
	}

	public DatabaseMetaData getMetaData() throws SQLException {
		return target.getMetaData();
	}

	public int getTransactionIsolation() throws SQLException {
		return target.getTransactionIsolation();
	}

	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return target.getTypeMap();
	}

	public SQLWarning getWarnings() throws SQLException {
		return target.getWarnings();
	}

	public boolean isClosed() throws SQLException {
		return target.isClosed();
	}

	public boolean isReadOnly() throws SQLException {
		return target.isReadOnly();
	}

	public String nativeSQL(String sql) throws SQLException {
		return target.nativeSQL(sql);
	}

	public CallableStatement prepareCall(String sql) throws SQLException {
		return target.prepareCall(sql);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return target.prepareCall(sql, resultSetType, resultSetConcurrency);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return target.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return target.prepareStatement(sql);
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return target.prepareStatement(sql, autoGeneratedKeys);
	}

	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return target.prepareStatement(sql, columnIndexes);
	}

	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return target.prepareStatement(sql, columnNames);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return target.prepareStatement(sql, resultSetType, resultSetConcurrency);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return target.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		target.releaseSavepoint(savepoint);
	}

	public void rollback() throws SQLException {
		target.rollback();
	}

	public void rollback(Savepoint savepoint) throws SQLException {
		target.rollback(savepoint);
	}

	public void setAutoCommit(boolean autoCommit) throws SQLException {
		target.setAutoCommit(autoCommit);
	}

	public void setCatalog(String catalog) throws SQLException {
		target.setCatalog(catalog);
	}

	public void setHoldability(int holdability) throws SQLException {
		target.setHoldability(holdability);
	}

	public void setReadOnly(boolean readOnly) throws SQLException {
		target.setReadOnly(readOnly);
	}

	public Savepoint setSavepoint() throws SQLException {
		return target.setSavepoint();
	}

	public Savepoint setSavepoint(String name) throws SQLException {
		return target.setSavepoint(name);
	}

	public void setTransactionIsolation(int level) throws SQLException {
		target.setTransactionIsolation(level);
	}

	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
		target.setTypeMap(map);
	}

}
