-- /!\ Pensez à nettoyer l'index également!
DECLARE

  numTiers NUMBER := 3035749;

BEGIN
    DELETE FROM EVENEMENT_FISCAL where TIERS_ID=numTiers;
    DELETE FROM DROIT_ACCES where TIERS_ID=numTiers;
    DELETE FROM MOUVEMENT_DOSSIER where CTB_ID=numTiers;
    DELETE FROM TACHE where CTB_ID=numTiers;
    DELETE FROM ETAT_DOCUMENT_FISCAL where DOCUMENT_FISCAL_ID in (select ID FROM DOCUMENT_FISCAL where TIERS_ID=numTiers);
    DELETE FROM DELAI_DOCUMENT_FISCAL where DOCUMENT_FISCAL_ID in (select ID FROM DOCUMENT_FISCAL where TIERS_ID=numTiers);
    DELETE FROM DOCUMENT_FISCAL where TIERS_ID=numTiers;
    DELETE FROM EVENEMENT_EXTERNE where TIERS_ID=numTiers;
    DELETE FROM REFERENCE_ANNONCE_IDE where ETABLISSEMENT_ID =numTiers;
    DELETE FROM FOR_FISCAL where TIERS_ID=numTiers;
    DELETE FROM ADRESSE_TIERS where TIERS_ID=numTiers or AUTRE_TIERS_ID=numTiers;
    DELETE FROM ADRESSE_MANDATAIRE where CTB_ID=numTiers;
    DELETE FROM IDENTIFICATION_ENTREPRISE where TIERS_ID=numTiers;
    DELETE FROM IDENTIFICATION_PERSONNE where NON_HABITANT_ID =numTiers;
    DELETE FROM SITUATION_FAMILLE where CTB_ID=numTiers;
    DELETE FROM RAPPORT_ENTRE_TIERS where TIERS_SUJET_ID= numTiers OR TIERS_OBJET_ID=numTiers OR TIERS_TUTEUR_ID=numTiers;
    DELETE FROM REMARQUE where TIERS_ID =numTiers;
    DELETE FROM PERIODICITE where DEBITEUR_ID=numTiers;
    DELETE FROM REQDES_PARTIE_PRENANTE where NO_CTB_CREE=numTiers OR  NO_CTB=numTiers;
    DELETE FROM DECISION_ACI where TIERS_ID =numTiers;
    DELETE FROM DOMICILE_ETABLISSEMENT where ETABLISSEMENT_ID =numTiers;
    DELETE FROM BOUCLEMENT where ENTREPRISE_ID=numTiers;
    DELETE FROM DONNEE_CIVILE_ENTREPRISE where ENTREPRISE_ID=numTiers;
    DELETE FROM FLAG_ENTREPRISE where ENTREPRISE_ID=numTiers;
    DELETE FROM REGIME_FISCAL where ENTREPRISE_ID=numTiers;
    DELETE FROM ALLEGEMENT_FISCAL  where ENTREPRISE_ID=numTiers;
    DELETE FROM ALLEGEMENT_FONCIER where CTB_ID=numTiers;
    DELETE FROM ETAT_ENTREPRISE where ENTREPRISE_ID=numTiers;
    DELETE FROM ETIQUETTE_TIERS where TIERS_ID =numTiers;
    DELETE FROM ETIQUETTE where COLADM_ID=numTiers;
    DELETE FROM RAPPROCHEMENT_RF where CTB_ID=numTiers;
    DELETE FROM DOCUMENT_EFACTURE where TIERS_ID =numTiers;
    DELETE FROM COORDONNEE_FINANCIERE where TIERS_ID =numTiers;
    DELETE FROM TIERS where NUMERO=numTiers;
    COMMIT;
END;
/