-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.5', '6.0.4_6.0.5_upgrade');

--
-- Déplacement du flag "établissement principal" sur le lien d'activité économique plutôt que sur l'établissement lui-même
-- (car un établissement peut être tour à tour principal et secondaire, en cas de démémagement de siège ou fusion d'entreprise,
-- par exemple...)
--

ALTER TABLE RAPPORT_ENTRE_TIERS ADD ETB_PRINCIPAL NUMBER(1,0);
UPDATE RAPPORT_ENTRE_TIERS RET SET RET.ETB_PRINCIPAL=(SELECT ETB_PRINCIPAL FROM TIERS T WHERE T.NUMERO=RET.TIERS_OBJET_ID AND T.TIERS_TYPE='Etablissement')
WHERE RET.RAPPORT_ENTRE_TIERS_TYPE='ActiviteEconomique';
ALTER TABLE TIERS DROP COLUMN ETB_PRINCIPAL;

--
-- Modèles de documents pour les DI PM/APM
-- (Aujourd'hui, nous mettons 2015 comme année charnière (pour les tests), mais il faudra sans doute mettre 2016 pour la MeP...)
--

INSERT INTO MODELE_DOCUMENT (ID, LOG_CDATE, LOG_MDATE, LOG_CUSER, LOG_MUSER, TYPE_DOCUMENT, PERIODE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, CURRENT_DATE, '[Installation SIPM]', '[Installation SIPM]', 'DECLARATION_IMPOT_PM', ID FROM PERIODE_FISCALE WHERE ANNEE >= 2015;
INSERT INTO MODELE_DOCUMENT (ID, LOG_CDATE, LOG_MDATE, LOG_CUSER, LOG_MUSER, TYPE_DOCUMENT, PERIODE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, CURRENT_DATE, '[Installation SIPM]', '[Installation SIPM]', 'DECLARATION_IMPOT_APM', ID FROM PERIODE_FISCALE WHERE ANNEE >= 2015;

--
-- Restructuration des paramètres spécifiques à une période fiscale pour les PM
--

DELETE FROM PARAMETRE_PERIODE_FISCALE WHERE PPF_TYPE='PM';
ALTER TABLE PARAMETRE_PERIODE_FISCALE DROP COLUMN PM_DELAI_IMPRIME_MANDATAIRE;
ALTER TABLE PARAMETRE_PERIODE_FISCALE DROP COLUMN PM_DELAI_EFF_MANDATAIRE;
ALTER TABLE PARAMETRE_PERIODE_FISCALE RENAME COLUMN PM_DELAI_IMPRIME TO PM_DELAI_IMPRIME_MOIS;
ALTER TABLE PARAMETRE_PERIODE_FISCALE RENAME COLUMN PM_DELAI_EFF TO PM_TOLERANCE_JOURS;
ALTER TABLE PARAMETRE_PERIODE_FISCALE ADD PM_DELAI_IMPRIME_FIN_MOIS NUMBER(1,0);
ALTER TABLE PARAMETRE_PERIODE_FISCALE ADD PM_TOLERANCE_FIN_MOIS NUMBER(1,0);
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, TYPE_CTB, PM_DELAI_IMPRIME_MOIS, PM_TOLERANCE_JOURS, PM_DELAI_IMPRIME_FIN_MOIS, PM_TOLERANCE_FIN_MOIS)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'PM', PF.ID, 'VAUDOIS_ORDINAIRE', 6, 75, 0, 0 FROM PERIODE_FISCALE PF;
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, TYPE_CTB, PM_DELAI_IMPRIME_MOIS, PM_TOLERANCE_JOURS, PM_DELAI_IMPRIME_FIN_MOIS, PM_TOLERANCE_FIN_MOIS)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'PM', PF.ID, 'HORS_CANTON', 6, 75, 0, 0 FROM PERIODE_FISCALE PF;
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, TYPE_CTB, PM_DELAI_IMPRIME_MOIS, PM_TOLERANCE_JOURS, PM_DELAI_IMPRIME_FIN_MOIS, PM_TOLERANCE_FIN_MOIS)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'PM', PF.ID, 'HORS_SUISSE', 6, 75, 0, 0 FROM PERIODE_FISCALE PF;

--
-- Nouveaux paramétrages pour les DI PM (distinction du délai administratif PP / PM)
--

UPDATE PARAMETRE SET NOM='delaiEnvoiSommationDeclarationImpotPP', LOG_MDATE=CURRENT_DATE, LOG_MUSER='[system-sipm]' WHERE NOM='delaiEnvoiSommationDeclarationImpot';
UPDATE PARAMETRE SET NOM='delaiEcheanceSommationDeclarationImpotPP', LOG_MDATE=CURRENT_DATE, LOG_MUSER='[system-sipm]' WHERE NOM='delaiEcheanceSommationDeclarationImpot';

--
-- Ménage sur la table des déclarations, des tiers
--

ALTER TABLE DECLARATION DROP COLUMN NOM_DOCUMENT;
ALTER TABLE TIERS DROP COLUMN REMARQUE;

--
-- Le capital, surchargeable, passe sur une table dédiée
--

CREATE TABLE CAPITAL_ENTREPRISE (
	ID NUMBER(19, 0) NOT NULL,
	ANNULATION_DATE TIMESTAMP,
	ANNULATION_USER NVARCHAR2(65),
	LOG_CDATE TIMESTAMP,
	LOG_CUSER NVARCHAR2(65),
	LOG_MDATE TIMESTAMP,
	LOG_MUSER NVARCHAR2(65),
	DATE_DEBUT NUMBER(10,0) NOT NULL,
	DATE_FIN NUMBER(10,0),
	MONTANT NUMBER(19,0) NOT NULL,
	MONNAIE NVARCHAR2(3) NOT NULL,
	ENTREPRISE_ID NUMBER(19,0) NOT NULL,
	PRIMARY KEY (ID)
);
ALTER TABLE CAPITAL_ENTREPRISE ADD CONSTRAINT FK_CAP_ENTRP_ID FOREIGN KEY (ENTREPRISE_ID) REFERENCES TIERS;
CREATE INDEX IDX_CAP_ENTRP_ID ON CAPITAL_ENTREPRISE (ENTREPRISE_ID ASC, DATE_DEBUT ASC);
INSERT INTO CAPITAL_ENTREPRISE (ID, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DATE_DEBUT, DATE_FIN, MONTANT, MONNAIE, ENTREPRISE_ID)
		SELECT HIBERNATE_SEQUENCE.NEXTVAL, ANNULATION_DATE, ANNULATION_USER, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, DATE_DEBUT, DATE_FIN, CAPITAL, MONNAIE_CAPITAL, ENTREPRISE_ID
			FROM DONNEES_RC WHERE CAPITAL IS NOT NULL AND MONNAIE_CAPITAL IS NOT NULL;
ALTER TABLE DONNEES_RC DROP COLUMN CAPITAL;
ALTER TABLE DONNEES_RC DROP COLUMN MONNAIE_CAPITAL;

--
-- les attributs temporels spécifiques aux entreprises (utilité publique, société immobilière...)
--

CREATE TABLE FLAG_ENTREPRISE (
	ID NUMBER(19, 0) NOT NULL,
	ANNULATION_DATE TIMESTAMP,
	ANNULATION_USER NVARCHAR2(65),
	LOG_CDATE TIMESTAMP,
	LOG_CUSER NVARCHAR2(65),
	LOG_MDATE TIMESTAMP,
	LOG_MUSER NVARCHAR2(65),
	ANNEE_DEBUT NUMBER(4,0) NOT NULL,
	ANNEE_FIN NUMBER(4,0),
	FLAG NVARCHAR2(20) NOT NULL,
	ENTREPRISE_ID NUMBER(19,0) NOT NULL,
	PRIMARY KEY (ID)
);
ALTER TABLE FLAG_ENTREPRISE ADD CONSTRAINT FK_FLAG_ENTRP_ID FOREIGN KEY (ENTREPRISE_ID) REFERENCES TIERS;
CREATE INDEX IDX_FLAG_ENTRP_ID ON FLAG_ENTREPRISE(ENTREPRISE_ID ASC, ANNEE_DEBUT ASC);

--
-- Transcription de la codification des régimes fiscaux
--

ALTER TABLE REGIME_FISCAL DROP COLUMN "TYPE";
ALTER TABLE REGIME_FISCAL ADD CODE NVARCHAR2(10);
UPDATE REGIME_FISCAL SET CODE='01';
ALTER TABLE REGIME_FISCAL MODIFY CODE NVARCHAR2(10) NOT NULL;

--
-- Suppression de la colonne DATE_FIN et renommage de DATE_DEBUT en DATE_OBTENTION sur les états d'entreprise
--

ALTER TABLE ETAT_ENTREPRISE DROP COLUMN DATE_FIN;
ALTER TABLE ETAT_ENTREPRISE RENAME COLUMN DATE_DEBUT TO DATE_OBTENTION;

--
-- Support de l'index de liste pour les erreurs d'événement organisation.
--
ALTER TABLE EVENEMENT_ORGANISATION_ERREUR ADD LIST_INDEX NUMBER(19,0);
UPDATE EVENEMENT_ORGANISATION_ERREUR SET LIST_INDEX = 0;
ALTER TABLE EVENEMENT_ORGANISATION_ERREUR MODIFY LIST_INDEX NUMBER(19,0) NOT NULL;
