-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.5', '6.0.4_6.0.5_upgrade');

--
-- Déplacement du flag "établissement principal" sur le lien d'activité économique plutôt que sur l'établissement lui-même
-- (car un établissement peut être tour à tour principal et secondaire, en cas de démémagement de siège ou fusion d'entreprise,
-- par exemple...)
--

ALTER TABLE RAPPORT_ENTRE_TIERS ADD ETB_PRINCIPAL NUMBER(1,0);
UPDATE RAPPORT_ENTRE_TIERS RET SET RET.ETB_PRINCIPAL=(SELECT ETB_PRINCIPAL FROM TIERS T WHERE T.NUMERO=RET.TIERS_OBJET_ID AND T.TIERS_TYPE='Etablissement')
WHERE RET.RAPPORT_ENTRE_TIERS_TYPE='ActiviteEconomique';
ALTER TABLE TIERS DROP COLUMN ETB_PRINCIPAL;

--
-- Modèles de documents pour les DI PM/APM
-- (Aujourd'hui, nous mettons 2015 comme année charnière (pour les tests), mais il faudra sans doute mettre 2016 pour la MeP...)
--

INSERT INTO MODELE_DOCUMENT (ID, LOG_CDATE, LOG_MDATE, LOG_CUSER, LOG_MUSER, TYPE_DOCUMENT, PERIODE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, CURRENT_DATE, '[Installation SIPM]', '[Installation SIPM]', 'DECLARATION_IMPOT_PM', ID FROM PERIODE_FISCALE WHERE ANNEE >= 2015;
INSERT INTO MODELE_DOCUMENT (ID, LOG_CDATE, LOG_MDATE, LOG_CUSER, LOG_MUSER, TYPE_DOCUMENT, PERIODE_ID)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, CURRENT_DATE, '[Installation SIPM]', '[Installation SIPM]', 'DECLARATION_IMPOT_APM', ID FROM PERIODE_FISCALE WHERE ANNEE >= 2015;

--
-- Restructuration des paramètres spécifiques à une période fiscale pour les PM
--

DELETE FROM PARAMETRE_PERIODE_FISCALE WHERE PPF_TYPE='PM';
ALTER TABLE PARAMETRE_PERIODE_FISCALE DROP COLUMN PM_DELAI_IMPRIME_MANDATAIRE;
ALTER TABLE PARAMETRE_PERIODE_FISCALE DROP COLUMN PM_DELAI_EFF_MANDATAIRE;
ALTER TABLE PARAMETRE_PERIODE_FISCALE RENAME COLUMN PM_DELAI_IMPRIME TO PM_DELAI_IMPRIME_MOIS;
ALTER TABLE PARAMETRE_PERIODE_FISCALE RENAME COLUMN PM_DELAI_EFF TO PM_TOLERANCE_JOURS;
ALTER TABLE PARAMETRE_PERIODE_FISCALE ADD PM_DELAI_IMPRIME_FIN_MOIS NUMBER(1,0);
ALTER TABLE PARAMETRE_PERIODE_FISCALE ADD PM_TOLERANCE_FIN_MOIS NUMBER(1,0);
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, TYPE_CTB, PM_DELAI_IMPRIME_MOIS, PM_TOLERANCE_JOURS, PM_DELAI_IMPRIME_FIN_MOIS, PM_TOLERANCE_FIN_MOIS)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'PM', PF.ID, 'VAUDOIS_ORDINAIRE', 6, 75, 0, 0 FROM PERIODE_FISCALE PF;
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, TYPE_CTB, PM_DELAI_IMPRIME_MOIS, PM_TOLERANCE_JOURS, PM_DELAI_IMPRIME_FIN_MOIS, PM_TOLERANCE_FIN_MOIS)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'PM', PF.ID, 'HORS_CANTON', 6, 75, 0, 0 FROM PERIODE_FISCALE PF;
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, PERIODE_ID, TYPE_CTB, PM_DELAI_IMPRIME_MOIS, PM_TOLERANCE_JOURS, PM_DELAI_IMPRIME_FIN_MOIS, PM_TOLERANCE_FIN_MOIS)
	SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation SIPM]', CURRENT_DATE, '[Installation SIPM]', 'PM', PF.ID, 'HORS_SUISSE', 6, 75, 0, 0 FROM PERIODE_FISCALE PF;

--
-- Nouveaux paramétrages pour les DI PM (distinction du délai administratif PP / PM)
--
UPDATE PARAMETRE SET NOM='delaiEnvoiSommationDeclarationImpotPP', LOG_MDATE=CURRENT_DATE, LOG_MUSER='[system-sipm]' WHERE NOM='delaiEnvoiSommationDeclarationImpot';
