-- script de conversion de la table ETAT_DECLARATION en NVARCHAR2 (écrit par Anastasiya SOTNYKOVA)

-- rename table , drop named constraints

ALTER TABLE etat_declaration
    RENAME TO etat_teclaration;
DROP INDEX IDX_ED_LOG_MDATE;
DROP INDEX IDX_ET_DI_DI_ID;
DROP INDEX IDX_ET_DI_SOMM_DI;
ALTER TABLE ETAT_TECLARATION
    DROP CONSTRAINT FK_ET_DI_DI_ID;

-- recreate table by select

CREATE TABLE etat_declaration
TABLESPACE UNIREG RESULT_CACHE (MODE DEFAULT) PCTUSED 0 PCTFREE 20 INITRANS 1 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MAXSIZE UNLIMITED MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
AS SELECT
       ID,
       ANNULATION_DATE,
       CAST(ANNULATION_USER AS NVARCHAR2(65)) ANNULATION_USER,
       LOG_CDATE,
       CAST(LOG_CUSER AS NVARCHAR2(65))       LOG_CUSER,
       LOG_MDATE,
       CAST(LOG_MUSER AS NVARCHAR2(65))       LOG_MUSER,
       DATE_OBTENTION,
       CAST(TYPE AS NVARCHAR2(12))            TYPE,
       DECLARATION_ID,
       DATE_ENVOI_COURRIER,
       SOURCE,
       EMOLUMENT,
       CLE_DOCUMENT
   FROM ETAT_TECLARATION;


CREATE INDEX IDX_ED_LOG_MDATE ON ETAT_DECLARATION (LOG_MDATE) LOGGING
TABLESPACE UNIREG PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MAXSIZE UNLIMITED MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT ) NOPARALLEL;

CREATE INDEX IDX_ET_DI_DI_ID ON ETAT_DECLARATION (DECLARATION_ID) LOGGING
TABLESPACE UNIREG PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MAXSIZE UNLIMITED MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) NOPARALLEL;

CREATE INDEX IDX_ET_DI_SOMM_DI ON ETAT_DECLARATION(DECLARATION_ID, ANNULATION_DATE, TYPE, DATE_OBTENTION) LOGGING
TABLESPACE UNIREG PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE (INITIAL 64K NEXT 1M MAXSIZE UNLIMITED MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) NOPARALLEL;

--  There is no statement for index UNIREG.SYS_C0010478.
--  The object is created when the parent object is created.

ALTER TABLE ETAT_DECLARATION ADD (PRIMARY KEY (ID) USING INDEX
        TABLESPACE UNIREG PCTFREE 10 INITRANS 2 MAXTRANS 255
        STORAGE (INITIAL 64K NEXT 1M MAXSIZE UNLIMITED MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE VALIDATE);

ALTER TABLE ETAT_DECLARATION ADD (CONSTRAINT FK_ET_DI_DI_ID FOREIGN KEY (DECLARATION_ID) REFERENCES DECLARATION (ID) ENABLE VALIDATE);

-- drop obsolete table

DROP TABLE ETAT_TECLARATION PURGE;
