-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.2.0', '6.1.1_6.2.0_upgrade');

--
-- [SIFISC-19984] Emoluments de sommation (50 CHF pour les DI PP dès 2016)
--

ALTER TABLE PARAMETRE_PERIODE_FISCALE ADD (EMOL_TYPE_DOCUMENT NVARCHAR2(15), EMOL_MONTANT NUMBER(8,0));
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, EMOL_TYPE_DOCUMENT, EMOL_MONTANT, PERIODE_ID)
		SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation 16R4]', CURRENT_DATE, '[Installation 16R4]', 'EMOL', 'SOMMATION_DI_PP', NULL, ID FROM PERIODE_FISCALE
		WHERE ANNEE < 2016;
INSERT INTO PARAMETRE_PERIODE_FISCALE (ID, LOG_CDATE, LOG_CUSER, LOG_MDATE, LOG_MUSER, PPF_TYPE, EMOL_TYPE_DOCUMENT, EMOL_MONTANT, PERIODE_ID)
		SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, '[Installation 16R4]', CURRENT_DATE, '[Installation 16R4]', 'EMOL', 'SOMMATION_DI_PP', 50, ID FROM PERIODE_FISCALE
		WHERE ANNEE >= 2016;

ALTER TABLE ETAT_DECLARATION ADD EMOLUMENT NUMBER(8,0);

--
-- [SIFISC-19535] Ajout d'une colonne COMMENTAIRE sur les tâches
--

ALTER TABLE TACHE ADD COMMENTAIRE NVARCHAR2(100);