-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('4.5.1', '4.5.0_4.5.1_upgrade');

--
-- Mouvements de dossiers en masse : drop oublié
ALTER TABLE MOUVEMENT_DOSSIER DROP COLUMN OID_EMETTEUR;

--
-- [UNIREG-2690] Annulation de tiers à une date donnée
--
UPDATE TIERS T SET ANNULATION_DATE=NULL, ANNULATION_USER=NULL
WHERE TO_CHAR(T.ANNULATION_DATE, 'HH24:MI:SS') = '00:00:00'
AND EXISTS (SELECT 1 FROM FOR_FISCAL FF WHERE FF.TIERS_ID = T.NUMERO AND FF.ANNULATION_DATE IS NULL AND FF.MOTIF_FERMETURE='ANNULATION' AND FF.DATE_FERMETURE = CAST(TO_CHAR(T.ANNULATION_DATE, 'YYYYMMDD') AS NUMBER));

--
-- [UNIREG-2735] Identification des DI dites "libres"
--
ALTER TABLE DECLARATION ADD (LIBRE number(1,0));
UPDATE DECLARATION SET LIBRE=0 WHERE DOCUMENT_TYPE='DI';
UPDATE DECLARATION SET LIBRE=1
WHERE ID IN (	SELECT DI.ID FROM DECLARATION DI JOIN PERIODE_FISCALE PF ON DI.PERIODE_ID=PF.ID AND PF.ANNEE=TO_CHAR(CURRENT_DATE,'YYYY')
				WHERE DI.ANNULATION_DATE IS NULL AND DI.DOCUMENT_TYPE='DI'
				AND NOT EXISTS (SELECT 1 FROM FOR_FISCAL FF WHERE FF.TIERS_ID=DI.TIERS_ID AND FF.ANNULATION_DATE IS NULL AND FF.DATE_FERMETURE=DI.DATE_FIN)
			);
