-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('4.5.1', '4.5.0_4.5.1_upgrade');

--
-- [UNIREG-2690] Annulation de tiers à une date donnée
--
UPDATE TIERS T SET ANNULATION_DATE=NULL, ANNULATION_USER=NULL
WHERE TO_CHAR(T.ANNULATION_DATE, 'HH24:MI:SS') = '00:00:00'
AND EXISTS (SELECT 1 FROM FOR_FISCAL FF WHERE FF.TIERS_ID = T.NUMERO AND FF.ANNULATION_DATE IS NULL AND FF.MOTIF_FERMETURE='ANNULATION' AND FF.DATE_FERMETURE = CAST(TO_CHAR(T.ANNULATION_DATE, 'YYYYMMDD') AS NUMBER));
