-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('19R1.A', '18R4.B_19R1.A_upgrade');

-- [SIFISC-30141] migration des numéros d'opérateur host vers les visa d'opérateur IAM
ALTER TABLE MOUVEMENT_DOSSIER ADD VISA_COLLABORATEUR NVARCHAR2(25);
CREATE INDEX IDX_VISA_COLLABORATEUR ON MOUVEMENT_DOSSIER (VISA_COLLABORATEUR ASC);
