-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('19R1.A', '18R4.B_19R1.A_upgrade');

-- [SIFISC-30141] migration des numéros d'opérateur host vers les visa d'opérateur IAM
ALTER TABLE MOUVEMENT_DOSSIER ADD VISA_COLLABORATEUR NVARCHAR2(25);
CREATE INDEX IDX_VISA_COLLABORATEUR ON MOUVEMENT_DOSSIER (VISA_COLLABORATEUR ASC);

-- [FISCPROJ-873] ajout du type de délai (implicite/explicite)
alter table DELAI_DOCUMENT_FISCAL rename column DELAI_TYPE to DISCRIMINATOR;
alter table DELAI_DOCUMENT_FISCAL add TYPE_DELAI NVARCHAR2(9) NULL;
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and LOG_MUSER = 'JMS-EvtDelaisDeclaration';
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and LOG_MUSER like 'zai%';
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and LOG_MUSER like 'ZAI%';
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and DEMANDE_MANDATAIRE_ID is not NULL ;
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'IMPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and TYPE_DELAI is null;

-- [FISCPROJ-506] paramètrisation des délais accordables pour les demandes de délais online (e-Délai)
alter table PARAMETRE_PERIODE_FISCALE modify PPF_TYPE NVARCHAR2(6);
alter table PARAMETRE_PERIODE_FISCALE add TYPE_TIERS NVARCHAR2(2) NULL;

create table PARAMETRE_DELAIS_ONLINE
(
    DISCRIMINATOR NVARCHAR2(31) not null,
    ID NUMBER(19) not null
        primary key,
    ANNULATION_DATE TIMESTAMP(6),
    ANNULATION_USER NVARCHAR2(65),
    LOG_CDATE TIMESTAMP(6),
    LOG_CUSER NVARCHAR2(65),
    LOG_MDATE TIMESTAMP(6),
    LOG_MUSER NVARCHAR2(65),
    DATE_DEBUT NUMBER(10),
    DATE_FIN NUMBER(10),
    INDEX_PERIODE NUMBER(10),
    DELAI_DEBUT NVARCHAR2(25),
    GROUPEE_PP NVARCHAR2(255),
    UNITAIRE_PP NVARCHAR2(255),
    GROUPEE_PM NVARCHAR2(255),
    UNITAIRE_PM NVARCHAR2(255),
    PARAM_PF_DELAI_ID NUMBER(19) not null
        constraint FK_PARAM_PF_DELAI_PERIODE_ID
        references PARAMETRE_PERIODE_FISCALE
);

create index IDX_PARAM_PF_DELAI_PERIODE_ID on PARAMETRE_DELAIS_ONLINE (PARAM_PF_DELAI_ID);

-- rattrapage de truc pas net
alter table PARAMETRE_PERIODE_FISCALE modify PERIODE_ID NOT NULL;
create index IDX_PARAM_PF_PERIODE_ID on PARAMETRE_PERIODE_FISCALE (PERIODE_ID);

-- initialisation des paramètres de délais pour la période fiscale 2017
insert into PARAMETRE_PERIODE_FISCALE(PPF_TYPE, ID, PERIODE_ID, TYPE_TIERS, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'ONLINE', HIBERNATE_SEQUENCE.NEXTVAL, pf.ID, 'PP', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PERIODE_FISCALE pf 
where pf.ANNEE = 2017;

insert into PARAMETRE_PERIODE_FISCALE(PPF_TYPE, ID, PERIODE_ID, TYPE_TIERS, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'ONLINE', HIBERNATE_SEQUENCE.NEXTVAL, pf.ID, 'PM', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PERIODE_FISCALE pf 
where pf.ANNEE = 2017;

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20180101, 20180515, '0630', '0630', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20180516, 20180615, '0630, 0930', '0630, 0930', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20180616, 20180831, '0930', null, 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20180901, 20181231, null, null, 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, INDEX_PERIODE, DELAI_DEBUT, UNITAIRE_PM, GROUPEE_PM, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PM', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 0, '0M', '6M + 75D', '6M + 75D', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PM' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, INDEX_PERIODE, DELAI_DEBUT, UNITAIRE_PM, GROUPEE_PM, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PM', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 1, '6M', '6M + 75D, 12M', '6M + 75D, 12M', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PM' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, INDEX_PERIODE, DELAI_DEBUT, UNITAIRE_PM, GROUPEE_PM, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PM', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 2, '9M', null, null, 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PM' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2017);

-- initialisation des paramètres de délais pour la période fiscale 2018
insert into PARAMETRE_PERIODE_FISCALE(PPF_TYPE, ID, PERIODE_ID, TYPE_TIERS, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'ONLINE', HIBERNATE_SEQUENCE.NEXTVAL, pf.ID, 'PP', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PERIODE_FISCALE pf
where pf.ANNEE = 2018;

insert into PARAMETRE_PERIODE_FISCALE(PPF_TYPE, ID, PERIODE_ID, TYPE_TIERS, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'ONLINE', HIBERNATE_SEQUENCE.NEXTVAL, pf.ID, 'PM', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PERIODE_FISCALE pf
where pf.ANNEE = 2018;

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20190101, 20190515, '0630', '0630', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20190516, 20190615, '0630, 0930', '0630, 0930', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20190616, 20190831, '0930', null, 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, DATE_DEBUT, DATE_FIN, UNITAIRE_PP, GROUPEE_PP, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PP', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 20190901, 20191231, null, null, 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PP' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, INDEX_PERIODE, DELAI_DEBUT, UNITAIRE_PM, GROUPEE_PM, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PM', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 0, '0M', '6M + 75D', '6M + 75D', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PM' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, INDEX_PERIODE, DELAI_DEBUT, UNITAIRE_PM, GROUPEE_PM, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PM', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 1, '6M', '6M + 75D, 12M', '6M + 75D, 12M', 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PM' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);

insert into PARAMETRE_DELAIS_ONLINE(DISCRIMINATOR, ID, PARAM_PF_DELAI_ID, INDEX_PERIODE, DELAI_DEBUT, UNITAIRE_PM, GROUPEE_PM, LOG_CUSER, LOG_CDATE, LOG_MUSER, LOG_MDATE)
select 'DI_PM', HIBERNATE_SEQUENCE.NEXTVAL, ppf.ID, 2, '9M', null, null, 'SQL-FISCPROJ-506', CURRENT_DATE, 'SQL-FISCPROJ-506', CURRENT_DATE
from PARAMETRE_PERIODE_FISCALE ppf
where ppf.PPF_TYPE = 'ONLINE' and ppf.TYPE_TIERS = 'PM' and ppf.PERIODE_ID = (select ID from PERIODE_FISCALE pf where pf.ANNEE = 2018);
