-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('19R1.A', '18R4.B_19R1.A_upgrade');

-- [SIFISC-30141] migration des numéros d'opérateur host vers les visa d'opérateur IAM
ALTER TABLE MOUVEMENT_DOSSIER ADD VISA_COLLABORATEUR NVARCHAR2(25);
CREATE INDEX IDX_VISA_COLLABORATEUR ON MOUVEMENT_DOSSIER (VISA_COLLABORATEUR ASC);

-- [FISCPROJ-873] ajout du type de délai (implicite/explicite)
alter table DELAI_DOCUMENT_FISCAL rename column DELAI_TYPE to DISCRIMINATOR;
alter table DELAI_DOCUMENT_FISCAL add TYPE_DELAI NVARCHAR2(9) NULL;
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and LOG_MUSER = 'JMS-EvtDelaisDeclaration';
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and LOG_MUSER like 'zai%';
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and LOG_MUSER like 'ZAI%';
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'EXPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and DEMANDE_MANDATAIRE_ID is not NULL ;
update DELAI_DOCUMENT_FISCAL set TYPE_DELAI = 'IMPLICITE' where DISCRIMINATOR = 'DELAI_DECLARATION' and TYPE_DELAI is null;