#! /bin/bash -
# Génération d'un script SQL qui va tenter d'enlever les PM dont l'identifiant est plus grand qu'une valeur donnée de la base Unireg

ID_MIN=$1
ID_MAX=999999
if [ -z "$ID_MIN" ]; then
	echo "Syntaxe : $(basename "$0") 80000 où 80000 est l'identifiant minimal (inclus) des PM à enlever de la base de données." >&2
	exit 1
elif [[ ! "$ID_MIN" =~ ^[0-9]{1,6}$ ]]; then
	echo "L'identifiant minimal des PM à enlevé doit comporter de 1 à 6 chiffres (trouvé : '$ID_MIN')." >&2
	exit 1
fi

cat <<-EOF
	
	-- on commence par les domiciles des établissements liés à ces PM
	DELETE FROM DOMICILE_ETABLISSEMENT
	WHERE ETABLISSEMENT_ID IN (SELECT TIERS_OBJET_ID FROM RAPPORT_ENTRE_TIERS RET WHERE TIERS_SUJET_ID BETWEEN $ID_MIN AND $ID_MAX AND RAPPORT_ENTRE_TIERS_TYPE='ActiviteEconomique');
	
	-- les adresses de ces mêmes établissements
	DELETE FROM ADRESSE_TIERS
	WHERE TIERS_ID IN (SELECT TIERS_OBJET_ID FROM RAPPORT_ENTRE_TIERS RET WHERE TIERS_SUJET_ID BETWEEN $ID_MIN AND $ID_MAX AND RAPPORT_ENTRE_TIERS_TYPE='ActiviteEconomique');
	
	--
	-- les établissements eux-mêmes (on les marque, puis on enlève les liens vers les entreprises, puis on les enlève eux-mêmes)
	--
	
	-- marquage
	UPDATE TIERS
	SET ANNULATION_DATE=CURRENT_DATE, ANNULATION_USER='SQL-remove'
	WHERE TIERS_TYPE='Etablissement'
	AND NUMERO IN (SELECT TIERS_OBJET_ID FROM RAPPORT_ENTRE_TIERS RET WHERE TIERS_SUJET_ID BETWEEN $ID_MIN AND $ID_MAX AND RAPPORT_ENTRE_TIERS_TYPE='ActiviteEconomique');
	
	-- destruction des rapports entre tiers autour de ces établissements marqués
	DELETE FROM RAPPORT_ENTRE_TIERS
	WHERE TIERS_OBJET_ID IN (SELECT NUMERO FROM TIERS WHERE TIERS_TYPE='Etablissement' AND ANNULATION_USER='SQL-remove');
	DELETE FROM RAPPORT_ENTRE_TIERS
	WHERE TIERS_SUJET_ID IN (SELECT NUMERO FROM TIERS WHERE TIERS_TYPE='Etablissement' AND ANNULATION_USER='SQL-remove');
	
	-- destruction des établissements eux-mêmes
	DELETE FROM TIERS WHERE TIERS_TYPE='Etablissement' AND ANNULATION_USER='SQL-remove';

	--
	-- les données des PM
	--

	-- rapports entre tiers
	DELETE FROM RAPPORT_ENTRE_TIERS WHERE TIERS_OBJET_ID BETWEEN $ID_MIN AND $ID_MAX;
	DELETE FROM RAPPORT_ENTRE_TIERS WHERE TIERS_SUJET_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les adresses
	DELETE FROM ADRESSE_TIERS WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les événements fiscaux
	DELETE FROM EVENEMENT_FISCAL WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les annonces RCEnt (j''enlève tout ??)
	DELETE FROM EVENEMENT_ORGANISATION_ERREUR
	WHERE EVT_ORGANISATION_ID IN (SELECT ID FROM EVENEMENT_ORGANISATION WHERE NO_ORGANISATION IN (SELECT NUMERO_ENTREPRISE FROM TIERS WHERE NUMERO BETWEEN $ID_MIN AND $ID_MAX AND NUMERO_ENTREPRISE IS NOT NULL));
	DELETE FROM EVENEMENT_ORGANISATION WHERE NO_ORGANISATION IN (SELECT NUMERO_ENTREPRISE FROM TIERS WHERE NUMERO BETWEEN $ID_MIN AND $ID_MAX AND NUMERO_ENTREPRISE IS NOT NULL);
	--DELETE FROM EVENEMENT_ORGANISATION_ERREUR;
	--DELETE FROM EVENEMENT_ORGANISATION;

	-- les fors
	DELETE FROM FOR_FISCAL WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les décisions ACI
	DELETE FROM DECISION_ACI WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les régimes fiscaux
	DELETE FROM REGIME_FISCAL WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les allègements fiscaux
	DELETE FROM ALLEGEMENT_FISCAL WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les cycles de bouclement
	DELETE FROM BOUCLEMENT WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les données RC
	DELETE FROM DONNEES_RC WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les données de capital des entreprises
	DELETE FROM CAPITAL_ENTREPRISE WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les états d''entreprise
	DELETE FROM ETAT_ENTREPRISE WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les flags d''entreprise
	DELETE FROM FLAG_ENTREPRISE WHERE ENTREPRISE_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les tâches
	DELETE FROM TACHE WHERE CTB_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les déclarations, leurs états et leurs délais
	DELETE FROM ETAT_DECLARATION WHERE DECLARATION_ID IN (SELECT ID FROM DECLARATION WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX);
	DELETE FROM DELAI_DECLARATION WHERE DECLARATION_ID IN (SELECT ID FROM DECLARATION WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX);
	DELETE FROM DECLARATION WHERE TIERS_ID BETWEEN $ID_MIN AND $ID_MAX;

	-- les entreprises elles-mêmes
	DELETE FROM TIERS WHERE NUMERO BETWEEN $ID_MIN AND $ID_MAX;

EOF
