-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('18R2.B', '18R2.A_18R2.B_upgrade');

-- IMM-1139 passage de 33 à 37 caractères la longueur des colonnes contenant des IDs RF.
ALTER TABLE EVENEMENT_RF_MUTATION MODIFY ID_RF NVARCHAR2(37);
ALTER TABLE EVENEMENT_RF_MUTATION MODIFY VERSION_RF NVARCHAR2(37);
ALTER TABLE RF_AYANT_DROIT MODIFY ID_RF NVARCHAR2(37);
ALTER TABLE RF_BATIMENT MODIFY MASTER_ID_RF NVARCHAR2(37);
ALTER TABLE RF_DROIT MODIFY MASTER_ID_RF NVARCHAR2(37);
ALTER TABLE RF_DROIT MODIFY VERSION_ID_RF NVARCHAR2(37);
ALTER TABLE RF_IMMEUBLE MODIFY ID_RF NVARCHAR2(37);