alter table IDENTIFICATION_PERSONNE modify (IDENTIFIANT varchar2(13 char));
alter table EVENEMENT_CIVIL_ERREUR modify (MESSAGE varchar2(1014 char));
create index IDX_ET_DI_SOMM_DI on ETAT_DECLARATION (DECLARATION_ID, ANNULATION_DATE, TYPE, DATE_OBTENTION);