-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('5.8.2', '5.7.0_5.8.2_upgrade');

-- Ajout des motifs de rattachement PHS et EFF (la longueur passe de 22 à 26)
ALTER TABLE FOR_FISCAL MODIFY MOTIF_RATTACHEMENT nvarchar2(26);

-- mise en place de nouveaux indexes
CREATE INDEX IDX_EVT_IDENT_CTB_PF_ETAT ON EVENEMENT_IDENTIFICATION_CTB(PERIODE_FISCALE, ETAT);
CREATE INDEX IDX_EVT_IDENT_CTB_EMTID_ETAT ON EVENEMENT_IDENTIFICATION_CTB(EMETTEUR_ID, ETAT);
CREATE INDEX IDX_EVT_IDENT_CTB_TM_DT_ETAT ON EVENEMENT_IDENTIFICATION_CTB(TYPE_MESSAGE, DEMANDE_TYPE, ETAT);