-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('18R3.A', '18R2.B_18R3.A_upgrade');

-- [IMM-795] historisation des liens servitudes-immeubles
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD ID NUMBER(19,0);
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD ANNULATION_DATE TIMESTAMP;
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD ANNULATION_USER NVARCHAR2(65);
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD LOG_CDATE TIMESTAMP;
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD LOG_CUSER NVARCHAR2(65);
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD LOG_MDATE TIMESTAMP;
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD LOG_MUSER NVARCHAR2(65);
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD DATE_DEBUT NUMBER(10,0);
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD DATE_FIN NUMBER(10,0);

-- gestion de l'id
ALTER TABLE RF_SERVITUDE_IMMEUBLE DROP PRIMARY KEY;
UPDATE RF_SERVITUDE_IMMEUBLE SET ID = hibernate_sequence.nextval;
ALTER TABLE RF_SERVITUDE_IMMEUBLE MODIFY ID NOT NULL;
ALTER TABLE RF_SERVITUDE_IMMEUBLE ADD CONSTRAINT PK_SERVITUDE_IMMEUBLE_ID PRIMARY KEY (ID);

-- rattrapage des dates de début et de fin
UPDATE RF_SERVITUDE_IMMEUBLE SET LOG_CUSER = 'SQL-IMM-795';
UPDATE RF_SERVITUDE_IMMEUBLE SET LOG_CDATE = CURRENT_DATE;
UPDATE RF_SERVITUDE_IMMEUBLE SET LOG_MUSER = 'SQL-IMM-795';
UPDATE RF_SERVITUDE_IMMEUBLE SET LOG_MDATE = CURRENT_DATE;
UPDATE RF_SERVITUDE_IMMEUBLE SET DATE_DEBUT = (select d.DATE_DEBUT_METIER from RF_DROIT d where d.id = DROIT_ID);
UPDATE RF_SERVITUDE_IMMEUBLE SET DATE_FIN = (select d.DATE_FIN_METIER from RF_DROIT d where d.id = DROIT_ID);

-- [IMM-795] historisation des liens servitudes-ayants-droits
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD ID NUMBER(19,0);
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD ANNULATION_DATE TIMESTAMP;
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD ANNULATION_USER NVARCHAR2(65);
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD LOG_CDATE TIMESTAMP;
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD LOG_CUSER NVARCHAR2(65);
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD LOG_MDATE TIMESTAMP;
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD LOG_MUSER NVARCHAR2(65);
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD DATE_DEBUT NUMBER(10,0);
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD DATE_FIN NUMBER(10,0);

-- gestion de l'id
ALTER TABLE RF_SERVITUDE_AYANT_DROIT DROP PRIMARY KEY;
UPDATE RF_SERVITUDE_AYANT_DROIT SET ID = hibernate_sequence.nextval;
ALTER TABLE RF_SERVITUDE_AYANT_DROIT MODIFY ID NOT NULL;
ALTER TABLE RF_SERVITUDE_AYANT_DROIT ADD CONSTRAINT PK_SERVITUDE_AYANT_DROIT_ID PRIMARY KEY (ID);

-- rattrapage des dates de début et de fin
UPDATE RF_SERVITUDE_AYANT_DROIT SET LOG_CUSER = 'SQL-IMM-795';
UPDATE RF_SERVITUDE_AYANT_DROIT SET LOG_CDATE = CURRENT_DATE;
UPDATE RF_SERVITUDE_AYANT_DROIT SET LOG_MUSER = 'SQL-IMM-795';
UPDATE RF_SERVITUDE_AYANT_DROIT SET LOG_MDATE = CURRENT_DATE;
UPDATE RF_SERVITUDE_AYANT_DROIT SET DATE_DEBUT = (select d.DATE_DEBUT_METIER from RF_DROIT d where d.id = DROIT_ID);
UPDATE RF_SERVITUDE_AYANT_DROIT SET DATE_FIN = (select d.DATE_FIN_METIER from RF_DROIT d where d.id = DROIT_ID);
