-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('3.4', '3.3.3_3.4_upgrade');

--
-- Script de modification des champs VARCHAR2 d'une base de données en NVARCHAR2
-- ATTENTION : l'exécution de cette partie du script est longue (1h44min sur une base proche de celle de la prod - au niveau contenu en tout cas)
--

-- Table VERSION_DB
ALTER TABLE VERSION_DB MODIFY (VERSION_NB NVARCHAR2(10), SCRIPT_ID NVARCHAR2(50));

-- Table ADRESSE_TIERS
ALTER TABLE ADRESSE_TIERS MODIFY (ADR_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), USAGE_TYPE NVARCHAR2(14), TYPE NVARCHAR2(14), STYPE NVARCHAR2(10), COMPLEMENT NVARCHAR2(100), NUMERO_APPARTEMENT NVARCHAR2(35), NUMERO_MAISON NVARCHAR2(35), RUE NVARCHAR2(100), TEXTE_CASE_POSTALE NVARCHAR2(15), COMPLEMENT_LOCALITE NVARCHAR2(100), NUMERO_POSTAL_LOCALITE NVARCHAR2(35));

-- Table AUDIT_LOG
ALTER TABLE AUDIT_LOG MODIFY (LOG_LEVEL NVARCHAR2(7), MESSAGE NVARCHAR2(255), LOG_USER NVARCHAR2(255));

-- Table DECLARATION
ALTER TABLE DECLARATION MODIFY (DOCUMENT_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), NOM_DOCUMENT NVARCHAR2(255), QUALIFICATION NVARCHAR2(16), TYPE_CTB NVARCHAR2(17), MODE_COM NVARCHAR2(12), PERIODICITE NVARCHAR2(11));

-- Table DELAI_DECLARATION
ALTER TABLE DELAI_DECLARATION MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65));

-- Table DOC_INDEX
ALTER TABLE DOC_INDEX MODIFY (DOC_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), DESCRIPTION NVARCHAR2(255), FILE_EXT NVARCHAR2(255), FILE_NAME NVARCHAR2(255), NOM NVARCHAR2(100), SUB_PATH NVARCHAR2(255));

-- Table DROIT_ACCES
ALTER TABLE DROIT_ACCES MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), NIVEAU NVARCHAR2(255), TYPE NVARCHAR2(255));

-- Table ETAT_DECLARATION
ALTER TABLE ETAT_DECLARATION MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), TYPE NVARCHAR2(12));

-- Table EVENEMENT_CIVIL_ERREUR
ALTER TABLE EVENEMENT_CIVIL_ERREUR MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), MESSAGE NVARCHAR2(1024), TYPE NVARCHAR2(7));

-- Table EVENEMENT_CIVIL_REGROUPE
ALTER TABLE EVENEMENT_CIVIL_REGROUPE MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), ETAT NVARCHAR2(10), TYPE NVARCHAR2(45));

-- Table EVENEMENT_CIVIL_UNITAIRE
ALTER TABLE EVENEMENT_CIVIL_UNITAIRE MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), ETAT NVARCHAR2(10), TYPE NVARCHAR2(60));

-- Table EVENEMENT_EXTERNE
ALTER TABLE EVENEMENT_EXTERNE MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), CORRELATION_ID NVARCHAR2(255), ERREUR_MESSAGE NVARCHAR2(255), ETAT NVARCHAR2(10));

-- Table EVENEMENT_FISCAL
ALTER TABLE EVENEMENT_FISCAL MODIFY (EVT_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), TYPE NVARCHAR2(29), MODE_IMPOSITION NVARCHAR2(11), MOTIF_FOR NVARCHAR2(49));

-- Table EVENEMENT_IDENTIFICATION_CTB
ALTER TABLE EVENEMENT_IDENTIFICATION_CTB MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), EMETTEUR_ID NVARCHAR2(50), MESSAGE_ID NVARCHAR2(36), NAVS11 NVARCHAR2(11), NAVS13 NVARCHAR2(13), ADR_CH_COMPL NVARCHAR2(2), ADR_CODE_PAYS NVARCHAR2(12), ADR_LIEU NVARCHAR2(40), ADR_LIGNE_1 NVARCHAR2(60), ADR_LIGNE_2 NVARCHAR2(60), ADR_LOCALITE NVARCHAR2(40), ADR_NO_APPART NVARCHAR2(10), ADR_NO_POLICE NVARCHAR2(12), ADR_NPA_ETRANGER NVARCHAR2(15), ADR_RUE NVARCHAR2(60), ADR_TEXT_CP NVARCHAR2(15), ADR_TYPE NVARCHAR2(255), NOM NVARCHAR2(100), PRENOMS NVARCHAR2(100), SEXE NVARCHAR2(8), PRIO_EMETTEUR NVARCHAR2(255), TYPE_MESSAGE NVARCHAR2(20), ETAT NVARCHAR2(23), BUSINESS_ID NVARCHAR2(255), BUSINESS_USER NVARCHAR2(255), REPLY_TO NVARCHAR2(255), ERREUR_CODE NVARCHAR2(20), ERREUR_MESSAGE NVARCHAR2(1000), ERREUR_TYPE NVARCHAR2(9));

-- Table FOR_FISCAL
ALTER TABLE FOR_FISCAL MODIFY (FOR_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), GENRE_IMPOT NVARCHAR2(29), TYPE_AUT_FISC NVARCHAR2(22), MOTIF_FERMETURE NVARCHAR2(49), MOTIF_OUVERTURE NVARCHAR2(49), MOTIF_RATTACHEMENT NVARCHAR2(22), MODE_IMPOSITION NVARCHAR2(11));

-- Table IDENTIFICATION_PERSONNE
ALTER TABLE IDENTIFICATION_PERSONNE MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), CATEGORIE NVARCHAR2(10), IDENTIFIANT NVARCHAR2(13));

-- Table LUCENE_IDX
ALTER TABLE LUCENE_IDX MODIFY (NAME_ NVARCHAR2(50));

-- Table LUCENE_IDX_HOST
ALTER TABLE LUCENE_IDX_HOST MODIFY (NAME_ NVARCHAR2(50));

-- Table MIGREG_ERROR
ALTER TABLE MIGREG_ERROR MODIFY (FOR_PRINCIPAL_CTB NVARCHAR2(255), LIBELLE_MESSAGE NVARCHAR2(255), NOM_CONTRIBUABLE NVARCHAR2(255), NOM_INDIVIDU NVARCHAR2(255));

-- Table MODELE_DOCUMENT
ALTER TABLE MODELE_DOCUMENT MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), TYPE_DOCUMENT NVARCHAR2(29));

-- Table MODELE_FEUILLE_DOC
ALTER TABLE MODELE_FEUILLE_DOC MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), INTITULE_FEUILLE NVARCHAR2(255), NO_FORMULAIRE NVARCHAR2(255));

-- Table MOUVEMENT_DOSSIER
ALTER TABLE MOUVEMENT_DOSSIER MODIFY (MVT_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), LOCALISATION NVARCHAR2(23));

-- Table PARAMETRE
ALTER TABLE PARAMETRE MODIFY (nom NVARCHAR2(255), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), valeur NVARCHAR2(255));

-- Table PARAMETRE_PERIODE_FISCALE
ALTER TABLE PARAMETRE_PERIODE_FISCALE MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), TYPE_CTB NVARCHAR2(17));

-- Table PERIODE_FISCALE
ALTER TABLE PERIODE_FISCALE MODIFY (ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65));

-- Table RAPPORT_ENTRE_TIERS
ALTER TABLE RAPPORT_ENTRE_TIERS MODIFY (RAPPORT_ENTRE_TIERS_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), TYPE_ACTIVITE NVARCHAR2(14));

-- Table SITUATION_FAMILLE
ALTER TABLE SITUATION_FAMILLE MODIFY (SITUATION_FAMILLE_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), ETAT_CIVIL NVARCHAR2(34), TARIF_APPLICABLE NVARCHAR2(11));

-- Table TACHE
ALTER TABLE TACHE MODIFY (TACHE_TYPE NVARCHAR2(15), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), ETAT NVARCHAR2(11), DECL_TYPE_CTB NVARCHAR2(17), DECL_TYPE_DOC NVARCHAR2(29));

-- Table TIERS
ALTER TABLE TIERS MODIFY (TIERS_TYPE NVARCHAR2(31), ANNULATION_USER NVARCHAR2(65), LOG_CUSER NVARCHAR2(65), LOG_MUSER NVARCHAR2(65), ADRESSE_BIC_SWIFT NVARCHAR2(15), ADRESSE_EMAIL NVARCHAR2(255), COMPLEMENT_NOM NVARCHAR2(250), NUMERO_COMPTE_BANCAIRE NVARCHAR2(34), NUMERO_TELECOPIE NVARCHAR2(35), NUMERO_TEL_PORTABLE NVARCHAR2(35), NUMERO_TEL_PRIVE NVARCHAR2(35), NUMERO_TEL_PROF NVARCHAR2(35), PERSONNE_CONTACT NVARCHAR2(200), REMARQUE NVARCHAR2(2000), TITULAIRE_COMPTE_BANCAIRE NVARCHAR2(200), AC_FORME_JURIDIQUE NVARCHAR2(5), AC_NOM NVARCHAR2(250), CATEGORIE_IMPOT_SOURCE NVARCHAR2(32), MODE_COM NVARCHAR2(12), DPI_NOM1 NVARCHAR2(250), DPI_NOM2 NVARCHAR2(250), PERIODE_DECOMPTE NVARCHAR2(3), PERIODICITE_DECOMPTE NVARCHAR2(11), NH_CAT_ETRANGER NVARCHAR2(35), NH_NOM NVARCHAR2(250), NH_NUMERO_ASSURE_SOCIAL NVARCHAR2(13), NH_PRENOM NVARCHAR2(250), NH_SEXE NVARCHAR2(8));


--
-- Modifications lies a la division de DECLARATION_IMPOT_COMPLETE en DECLARATION_IMPOT_COMPLETE_BATCH et DECLARATION_IMPOT_COMPLETE_LOCAL
--
 
ALTER TABLE MODELE_DOCUMENT MODIFY (TYPE_DOCUMENT NVARCHAR2(32));
ALTER TABLE TACHE MODIFY (DECL_TYPE_DOC NVARCHAR2(32));

UPDATE MODELE_DOCUMENT SET TYPE_DOCUMENT='DECLARATION_IMPOT_COMPLETE_BATCH' WHERE TYPE_DOCUMENT='DECLARATION_IMPOT_COMPLETE';

UPDATE TACHE SET DECL_TYPE_DOC='DECLARATION_IMPOT_COMPLETE_BATCH' WHERE DECL_TYPE_DOC='DECLARATION_IMPOT_COMPLETE';

INSERT INTO MODELE_DOCUMENT (id, log_cdate, log_cuser, log_mdate, log_muser, type_document, periode_id)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, 'schema-3.4', CURRENT_DATE, 'schema-3.4', 'DECLARATION_IMPOT_COMPLETE_LOCAL', periode_id
FROM MODELE_DOCUMENT
WHERE TYPE_DOCUMENT='DECLARATION_IMPOT_COMPLETE_BATCH'
AND ANNULATION_DATE IS NULL;

INSERT INTO MODELE_FEUILLE_DOC (id, log_cdate, log_cuser, log_mdate, log_muser, intitule_feuille, no_formulaire, modele_id)
SELECT HIBERNATE_SEQUENCE.NEXTVAL, CURRENT_DATE, 'schema-3.4', CURRENT_DATE, 'schema-3.4', MFD.intitule_feuille, MFD.no_formulaire, MD_DEST.id
FROM MODELE_FEUILLE_DOC MFD
JOIN MODELE_DOCUMENT MD_SRC ON MFD.MODELE_ID = MD_SRC.ID AND MD_SRC.TYPE_DOCUMENT='DECLARATION_IMPOT_COMPLETE_BATCH'
JOIN MODELE_DOCUMENT MD_DEST ON MD_SRC.PERIODE_ID = MD_DEST.PERIODE_ID AND MD_DEST.TYPE_DOCUMENT='DECLARATION_IMPOT_COMPLETE_LOCAL'
WHERE MFD.ANNULATION_DATE IS NULL;

DELETE FROM MODELE_FEUILLE_DOC
WHERE ID IN (SELECT MFD.ID
             FROM MODELE_FEUILLE_DOC MFD
             JOIN MODELE_DOCUMENT MD ON MFD.MODELE_ID = MD.ID
             JOIN PERIODE_FISCALE PF ON MD.PERIODE_ID = PF.ID
             WHERE PF.ANNEE >= 2009 AND MFD.NO_FORMULAIRE=310 AND MD.TYPE_DOCUMENT='DECLARATION_IMPOT_COMPLETE_BATCH');

--
-- Exclusion des contribuables
--
alter table TIERS add (DATE_LIMITE_EXCLUSION number(10,0));
