-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.0.3', '7.0.2_7.0.3_upgrade');

--
-- [SIFISC-22997] Calcul des dates de fin métier sur les droits
--
ALTER TABLE RF_DROIT RENAME COLUMN DATE_DEBUT_OFFICIELLE TO DATE_DEBUT_METIER;
ALTER TABLE RF_DROIT ADD DATE_FIN_METIER NUMBER(10) NULL;

--
-- [SIFISC-23478] Calcul et stockage de l'année de référence des estimations fiscales
--
ALTER TABLE RF_ESTIMATION ADD ANNEE_REFERENCE NUMBER(10) NULL;