-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.1.1', '7.1.0_7.1.1_upgrade');

-- [SIFISC-23908] Ajout d'un flag "contrôle office logement" sur les données de dégrèvement ICI
ALTER TABLE ALLEGEMENT_FONCIER ADD DEG_LL_CTRL_OFFICE_LOGEMENT NUMBER(1,0) NULL;
UPDATE ALLEGEMENT_FONCIER SET DEG_LL_CTRL_OFFICE_LOGEMENT=1 WHERE DEG_LL_CARAC_SOCIAL_POURCENT IS NOT NULL OR DEG_LL_ECHEANCE IS NOT NULL OR DEG_LL_OCTROI IS NOT NULL;
UPDATE ALLEGEMENT_FONCIER SET DEG_LL_CTRL_OFFICE_LOGEMENT=0 WHERE TYPE_ALLEGEMENT='DegrevementICI' AND DEG_LL_CTRL_OFFICE_LOGEMENT IS NULL;

-- [SIFISC-23908] Ajout d'un flag "erreur d'intégration" sur les données de dégrèvement ICI
ALTER TABLE ALLEGEMENT_FONCIER ADD DEG_NON_INTEGRABLE NUMBER(1,0) NULL;
UPDATE ALLEGEMENT_FONCIER SET DEG_NON_INTEGRABLE=0 WHERE TYPE_ALLEGEMENT='DegrevementICI';