-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('7.1.1', '7.1.0_7.1.1_upgrade');

-- [SIFISC-23908] Ajout d'un flag "contrôle office logement" sur les données de dégrèvement ICI
ALTER TABLE ALLEGEMENT_FONCIER ADD DEG_LL_CTRL_OFFICE_LOGEMENT NUMBER(1,0) NULL;
UPDATE ALLEGEMENT_FONCIER SET DEG_LL_CTRL_OFFICE_LOGEMENT=1 WHERE DEG_LL_CARAC_SOCIAL_POURCENT IS NOT NULL OR DEG_LL_ECHEANCE IS NOT NULL OR DEG_LL_OCTROI IS NOT NULL;
UPDATE ALLEGEMENT_FONCIER SET DEG_LL_CTRL_OFFICE_LOGEMENT=0 WHERE TYPE_ALLEGEMENT='DegrevementICI' AND DEG_LL_CTRL_OFFICE_LOGEMENT IS NULL;

-- [SIFISC-23908] Ajout d'un flag "erreur d'intégration" sur les données de dégrèvement ICI
ALTER TABLE ALLEGEMENT_FONCIER ADD DEG_NON_INTEGRABLE NUMBER(1,0) NULL;
UPDATE ALLEGEMENT_FONCIER SET DEG_NON_INTEGRABLE=0 WHERE TYPE_ALLEGEMENT='DegrevementICI';

-- [SIFISC-23894] ajout des raisons d'acquisition
CREATE TABLE RF_RAISON_ACQUISITION
(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    ANNULATION_DATE TIMESTAMP(6),
    ANNULATION_USER NVARCHAR2(65),
    LOG_CDATE TIMESTAMP(6),
    LOG_CUSER NVARCHAR2(65),
    LOG_MDATE TIMESTAMP(6),
    LOG_MUSER NVARCHAR2(65),
    DATE_ACQUISITION NUMBER(10),
    MOTIF_ACQUISITION NVARCHAR2(255),
    NO_AFFAIRE NVARCHAR2(40),
    DROIT_ID NUMBER(19) NOT NULL,
    CONSTRAINT FK_RAISON_ACQ_RF_IMMEUBLE_ID FOREIGN KEY (DROIT_ID) REFERENCES RF_DROIT (ID)
);
CREATE INDEX IDX_RAISON_ACQ_RF_DROIT_ID ON RF_RAISON_ACQUISITION (DROIT_ID);

-- [SIFISC-23957] re-écriture du modèle de données des servitudes
ALTER TABLE RF_DROIT MODIFY AYANT_DROIT_ID NULL;
ALTER TABLE RF_DROIT MODIFY IMMEUBLE_ID NULL;
DROP INDEX IDX_DROIT_MASTER_ID_RF;
CREATE UNIQUE INDEX IDX_DROIT_MASTER_ID_RF ON RF_DROIT(MASTER_ID_RF);

CREATE TABLE RF_SERVITUDE_AYANT_DROIT
(
    DROIT_ID NUMBER(19) NOT NULL,
    AYANT_DROIT_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_SERV_AD_RF PRIMARY KEY (DROIT_ID, AYANT_DROIT_ID),
    CONSTRAINT FK_SERV_AD_RF_DROIT_ID FOREIGN KEY (DROIT_ID) REFERENCES RF_DROIT (ID),
    CONSTRAINT FK_SERV_AD_RF_AYANT_DROIT_ID FOREIGN KEY (AYANT_DROIT_ID) REFERENCES RF_AYANT_DROIT (ID)
);

CREATE TABLE RF_SERVITUDE_IMMEUBLE
(
    DROIT_ID NUMBER(19) NOT NULL,
    IMMEUBLE_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_SERV_IMM_RF PRIMARY KEY (DROIT_ID, IMMEUBLE_ID),
    CONSTRAINT FK_SERV_IMM_RF_DROIT_ID FOREIGN KEY (DROIT_ID) REFERENCES RF_DROIT (ID),
    CONSTRAINT FK_SERV_IMM_RF_IMMEUBLE_ID FOREIGN KEY (IMMEUBLE_ID) REFERENCES RF_IMMEUBLE (ID)
);
