package ch.vd.uniregctb.migration.pm.regpm;

public enum RegpmCodeContribution {
	BENEFICE,
	CAPITAL,
	REVENU_PRENUMERANDO,
	BENEFICE_EXTRAORDINAIRE,
	IMPOT_BENEFICE_CAPITAL,
	IMPOT_MINIMUM_RECETTES_BRUTES,
	IMPOT_MINIMUM_CAPITAUX_INVESTIS,
	IMPOT_COMPLEMENTAIRE_IMMEUBLES,
	AMENDE_DEFAUT_DOSSIER,
	AMENDE_DEFAUT_PIECE,
	AMENDE_SOUSTRACTION,
	IMPOT_FORTUNE,
	DROIT_ENTIER,
	DEMI_DROIT,
	INCENDIE_BATIMENT,
	TAXE_EPURATION_EAUX,
	TAXE_EGOUT,
	TAXE_ORDURES,
	IMPOT_FONCIER_SOL_AUTRUI,
	FOURNITURE_EAU,
	IMPOT_FONCIER,
	GAINS_IMMOBILIERS,
	PERCU_APRES_DEFALCATION,
	AMENDE_PARTICIPATION_SOUSTRACTION,
	REMBOURSEMENT_IMPOT_COMPLEMENTAIRE_IMMEUBLES
}
