package ch.vd.uniregctb.migration.pm.regpm;

public enum RegpmFonction {
	PRESIDENT,
	VICE_PRESIDENT,
	SECRETAIRE,
	TRESORIER,
	CAISSIER,
	ASSOCIE_INDEF_RESP,
	COMMANDITAIRE,
	ASSOCIE_GERANT,
	ASSOCIE,
	RESPONSABLE_SUCCURSALE,
	ADMINISTRATEUR,
	CURATEUR,
	DIRECTEUR,
	SOUS_DIRECTEUR,
	LIQUIDATEUR
}
