-- Version
INSERT INTO VERSION_DB (VERSION_NB, SCRIPT_ID) VALUES ('6.0.8', '6.0.7_6.0.8_upgrade');

-- le rapport d'administration d'entreprise a besoin d'un attribut supplémentaire (rôle de 'président')
ALTER TABLE RAPPORT_ENTRE_TIERS ADD ADMIN_PRESIDENT NUMBER(1,0);

-- Changement dans les mappings des types d'allègement
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_ICC='EXONERATION_90LI' WHERE TYPE_ALLEGEMENT_ICC IN ('ARTICLE_90IG_LI', 'ARTICLE_90H_LI', 'ARTICLE_90C_LI', 'ARTICLE_90E_LI', 'ARTICLE_90F_LI');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_ICC='TEMPORAIRE_91LI' WHERE TYPE_ALLEGEMENT_ICC IN ('ARTICLE_91_LI');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_ICC='EXONERATION_SPECIALE' WHERE TYPE_ALLEGEMENT_ICC IN ('SOCIETE_MEXICAINE');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_ICC='SOCIETE_SERVICE' WHERE TYPE_ALLEGEMENT_ICC IN ('SOCIETE_DE_BASE');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_ICC='IMMEUBLE_SI_SUBVENTIONNEE' WHERE TYPE_ALLEGEMENT_ICC IN ('IMMEUBLE_SOC_IMMOB_SUBV');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_IFD='TEMPORAIRE_91LI' WHERE TYPE_ALLEGEMENT_IFD IN ('DECISION_DFE');
UPDATE ALLEGEMENT_FISCAL SET TYPE_ALLEGEMENT_IFD='EXONERATION_SPECIALE' WHERE TYPE_ALLEGEMENT_IFD IN ('AUTRE_TYPE');

-- [SIFISC-17979] nouveaux champs sur les mandats
ALTER TABLE RAPPORT_ENTRE_TIERS ADD (NOM_CONTACT_MANDAT NVARCHAR2(50), PRENOM_CONTACT_MANDAT NVARCHAR2(50), TEL_CONTACT_MANDAT NVARCHAR2(35));
